import logo from './logo.svg';
import './App.css';
import Main from './components/Main';

function App() {
  let data=[
    {
      "Country/Region": "USA",
      "Continent": "North America",
      "Population": 331198130,
      "TotalCases": 5032179,
      "NewCases": "",
      "TotalDeaths": 162804,
      "NewDeaths": "",
      "TotalRecovered": 2576668,
      "NewRecovered": "",
      "ActiveCases": 2292707,
      "Serious,Critical": 18296,
      "Tot Cases/1M pop": 15194,
      "Deaths/1M pop": 492,
      "TotalTests": 63139605,
      "Tests/1M pop": 190640,
      "WHO Region": "Americas"
    },
    {
      "Country/Region": "Brazil",
      "Continent": "South America",
      "Population": 212710692,
      "TotalCases": 2917562,
      "NewCases": "",
      "TotalDeaths": 98644,
      "NewDeaths": "",
      "TotalRecovered": 2047660,
      "NewRecovered": "",
      "ActiveCases": 771258,
      "Serious,Critical": 8318,
      "Tot Cases/1M pop": 13716,
      "Deaths/1M pop": 464,
      "TotalTests": 13206188,
      "Tests/1M pop": 62085,
      "WHO Region": "Americas"
    },
    {
      "Country/Region": "India",
      "Continent": "Asia",
      "Population": 1381344997,
      "TotalCases": 2025409,
      "NewCases": "",
      "TotalDeaths": 41638,
      "NewDeaths": "",
      "TotalRecovered": 1377384,
      "NewRecovered": "",
      "ActiveCases": 606387,
      "Serious,Critical": 8944,
      "Tot Cases/1M pop": 1466,
      "Deaths/1M pop": 30,
      "TotalTests": 22149351,
      "Tests/1M pop": 16035,
      "WHO Region": "South-EastAsia"
    },
    {
      "Country/Region": "Russia",
      "Continent": "Europe",
      "Population": 145940924,
      "TotalCases": 871894,
      "NewCases": "",
      "TotalDeaths": 14606,
      "NewDeaths": "",
      "TotalRecovered": 676357,
      "NewRecovered": "",
      "ActiveCases": 180931,
      "Serious,Critical": 2300,
      "Tot Cases/1M pop": 5974,
      "Deaths/1M pop": 100,
      "TotalTests": 29716907,
      "Tests/1M pop": 203623,
      "WHO Region": "Europe"
    },
    {
      "Country/Region": "South Africa",
      "Continent": "Africa",
      "Population": 59381566,
      "TotalCases": 538184,
      "NewCases": "",
      "TotalDeaths": 9604,
      "NewDeaths": "",
      "TotalRecovered": 387316,
      "NewRecovered": "",
      "ActiveCases": 141264,
      "Serious,Critical": 539,
      "Tot Cases/1M pop": 9063,
      "Deaths/1M pop": 162,
      "TotalTests": 3149807,
      "Tests/1M pop": 53044,
      "WHO Region": "Africa"
    },
    {
      "Country/Region": "Mexico",
      "Continent": "North America",
      "Population": 129066160,
      "TotalCases": 462690,
      "NewCases": 6590,
      "TotalDeaths": 50517,
      "NewDeaths": 819,
      "TotalRecovered": 308848,
      "NewRecovered": 4140,
      "ActiveCases": 103325,
      "Serious,Critical": 3987,
      "Tot Cases/1M pop": 3585,
      "Deaths/1M pop": 391,
      "TotalTests": 1056915,
      "Tests/1M pop": 8189,
      "WHO Region": "Americas"
    },
    {
      "Country/Region": "Peru",
      "Continent": "South America",
      "Population": 33016319,
      "TotalCases": 455409,
      "NewCases": "",
      "TotalDeaths": 20424,
      "NewDeaths": "",
      "TotalRecovered": 310337,
      "NewRecovered": "",
      "ActiveCases": 124648,
      "Serious,Critical": 1426,
      "Tot Cases/1M pop": 13793,
      "Deaths/1M pop": 619,
      "TotalTests": 2493429,
      "Tests/1M pop": 75521,
      "WHO Region": "Americas"
    },
    {
      "Country/Region": "Chile",
      "Continent": "South America",
      "Population": 19132514,
      "TotalCases": 366671,
      "NewCases": "",
      "TotalDeaths": 9889,
      "NewDeaths": "",
      "TotalRecovered": 340168,
      "NewRecovered": "",
      "ActiveCases": 16614,
      "Serious,Critical": 1358,
      "Tot Cases/1M pop": 19165,
      "Deaths/1M pop": 517,
      "TotalTests": 1760615,
      "Tests/1M pop": 92022,
      "WHO Region": "Americas"
    },
    {
      "Country/Region": "Colombia",
      "Continent": "South America",
      "Population": 50936262,
      "TotalCases": 357710,
      "NewCases": "",
      "TotalDeaths": 11939,
      "NewDeaths": "",
      "TotalRecovered": 192355,
      "NewRecovered": "",
      "ActiveCases": 153416,
      "Serious,Critical": 1493,
      "Tot Cases/1M pop": 7023,
      "Deaths/1M pop": 234,
      "TotalTests": 1801835,
      "Tests/1M pop": 35374,
      "WHO Region": "Americas"
    },
    {
      "Country/Region": "Spain",
      "Continent": "Europe",
      "Population": 46756648,
      "TotalCases": 354530,
      "NewCases": "",
      "TotalDeaths": 28500,
      "NewDeaths": "",
      "TotalRecovered": "",
      "NewRecovered": "",
      "ActiveCases": "",
      "Serious,Critical": 617,
      "Tot Cases/1M pop": 7582,
      "Deaths/1M pop": 610,
      "TotalTests": 7064329,
      "Tests/1M pop": 151087,
      "WHO Region": "Europe"
    },
    {
      "Country/Region": "Iran",
      "Continent": "Asia",
      "Population": 84097623,
      "TotalCases": 320117,
      "NewCases": "",
      "TotalDeaths": 17976,
      "NewDeaths": "",
      "TotalRecovered": 277463,
      "NewRecovered": "",
      "ActiveCases": 24678,
      "Serious,Critical": 4156,
      "Tot Cases/1M pop": 3806,
      "Deaths/1M pop": 214,
      "TotalTests": 2612763,
      "Tests/1M pop": 31068,
      "WHO Region": "EasternMediterranean"
    },
    {
      "Country/Region": "UK",
      "Continent": "Europe",
      "Population": 67922029,
      "TotalCases": 308134,
      "NewCases": "",
      "TotalDeaths": 46413,
      "NewDeaths": "",
      "TotalRecovered": "",
      "NewRecovered": "",
      "ActiveCases": "",
      "Serious,Critical": 73,
      "Tot Cases/1M pop": 4537,
      "Deaths/1M pop": 683,
      "TotalTests": 17515234,
      "Tests/1M pop": 257873,
      "WHO Region": "Europe"
    },
    {
      "Country/Region": "Saudi Arabia",
      "Continent": "Asia",
      "Population": 34865919,
      "TotalCases": 284226,
      "NewCases": "",
      "TotalDeaths": 3055,
      "NewDeaths": "",
      "TotalRecovered": 247089,
      "NewRecovered": "",
      "ActiveCases": 34082,
      "Serious,Critical": 1915,
      "Tot Cases/1M pop": 8152,
      "Deaths/1M pop": 88,
      "TotalTests": 3635705,
      "Tests/1M pop": 104277,
      "WHO Region": "EasternMediterranean"
    },
    {
      "Country/Region": "Pakistan",
      "Continent": "Asia",
      "Population": 221295851,
      "TotalCases": 281863,
      "NewCases": "",
      "TotalDeaths": 6035,
      "NewDeaths": "",
      "TotalRecovered": 256058,
      "NewRecovered": "",
      "ActiveCases": 19770,
      "Serious,Critical": 809,
      "Tot Cases/1M pop": 1274,
      "Deaths/1M pop": 27,
      "TotalTests": 2058872,
      "Tests/1M pop": 9304,
      "WHO Region": "EasternMediterranean"
    },
    {
      "Country/Region": "Bangladesh",
      "Continent": "Asia",
      "Population": 164851401,
      "TotalCases": 249651,
      "NewCases": "",
      "TotalDeaths": 3306,
      "NewDeaths": "",
      "TotalRecovered": 143824,
      "NewRecovered": "",
      "ActiveCases": 102521,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 1514,
      "Deaths/1M pop": 20,
      "TotalTests": 1225124,
      "Tests/1M pop": 7432,
      "WHO Region": "South-EastAsia"
    },
    {
      "Country/Region": "Italy",
      "Continent": "Europe",
      "Population": 60452568,
      "TotalCases": 249204,
      "NewCases": "",
      "TotalDeaths": 35187,
      "NewDeaths": "",
      "TotalRecovered": 201323,
      "NewRecovered": "",
      "ActiveCases": 12694,
      "Serious,Critical": 42,
      "Tot Cases/1M pop": 4122,
      "Deaths/1M pop": 582,
      "TotalTests": 7099713,
      "Tests/1M pop": 117443,
      "WHO Region": "Europe"
    },
    {
      "Country/Region": "Turkey",
      "Continent": "Asia",
      "Population": 84428331,
      "TotalCases": 237265,
      "NewCases": "",
      "TotalDeaths": 5798,
      "NewDeaths": "",
      "TotalRecovered": 220546,
      "NewRecovered": "",
      "ActiveCases": 10921,
      "Serious,Critical": 580,
      "Tot Cases/1M pop": 2810,
      "Deaths/1M pop": 69,
      "TotalTests": 5081802,
      "Tests/1M pop": 60191,
      "WHO Region": "Europe"
    },
    {
      "Country/Region": "Argentina",
      "Continent": "South America",
      "Population": 45236884,
      "TotalCases": 228195,
      "NewCases": "",
      "TotalDeaths": 4251,
      "NewDeaths": "",
      "TotalRecovered": 99852,
      "NewRecovered": "",
      "ActiveCases": 124092,
      "Serious,Critical": 1150,
      "Tot Cases/1M pop": 5044,
      "Deaths/1M pop": 94,
      "TotalTests": 794544,
      "Tests/1M pop": 17564,
      "WHO Region": "Americas"
    },
    {
      "Country/Region": "Germany",
      "Continent": "Europe",
      "Population": 83811260,
      "TotalCases": 215210,
      "NewCases": "",
      "TotalDeaths": 9252,
      "NewDeaths": "",
      "TotalRecovered": 196200,
      "NewRecovered": "",
      "ActiveCases": 9758,
      "Serious,Critical": 236,
      "Tot Cases/1M pop": 2568,
      "Deaths/1M pop": 110,
      "TotalTests": 8586648,
      "Tests/1M pop": 102452,
      "WHO Region": "Europe"
    },
    {
      "Country/Region": "France",
      "Continent": "Europe",
      "Population": 65288306,
      "TotalCases": 195633,
      "NewCases": "",
      "TotalDeaths": 30312,
      "NewDeaths": "",
      "TotalRecovered": 82460,
      "NewRecovered": "",
      "ActiveCases": 82861,
      "Serious,Critical": 384,
      "Tot Cases/1M pop": 2996,
      "Deaths/1M pop": 464,
      "TotalTests": 3992206,
      "Tests/1M pop": 61147,
      "WHO Region": "Europe"
    },
    {
      "Country/Region": "Iraq",
      "Continent": "Asia",
      "Population": 40306025,
      "TotalCases": 140603,
      "NewCases": "",
      "TotalDeaths": 5161,
      "NewDeaths": "",
      "TotalRecovered": 101025,
      "NewRecovered": "",
      "ActiveCases": 34417,
      "Serious,Critical": 517,
      "Tot Cases/1M pop": 3488,
      "Deaths/1M pop": 128,
      "TotalTests": 1092741,
      "Tests/1M pop": 27111,
      "WHO Region": "EasternMediterranean"
    },
    {
      "Country/Region": "Philippines",
      "Continent": "Asia",
      "Population": 109722719,
      "TotalCases": 119460,
      "NewCases": "",
      "TotalDeaths": 2150,
      "NewDeaths": "",
      "TotalRecovered": 66837,
      "NewRecovered": "",
      "ActiveCases": 50473,
      "Serious,Critical": 239,
      "Tot Cases/1M pop": 1089,
      "Deaths/1M pop": 20,
      "TotalTests": 1669996,
      "Tests/1M pop": 15220,
      "WHO Region": "WesternPacific"
    },
    {
      "Country/Region": "Indonesia",
      "Continent": "Asia",
      "Population": 273808365,
      "TotalCases": 118753,
      "NewCases": "",
      "TotalDeaths": 5521,
      "NewDeaths": "",
      "TotalRecovered": 75645,
      "NewRecovered": "",
      "ActiveCases": 37587,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 434,
      "Deaths/1M pop": 20,
      "TotalTests": 1633156,
      "Tests/1M pop": 5965,
      "WHO Region": "South-EastAsia"
    },
    {
      "Country/Region": "Canada",
      "Continent": "North America",
      "Population": 37775022,
      "TotalCases": 118561,
      "NewCases": "",
      "TotalDeaths": 8966,
      "NewDeaths": "",
      "TotalRecovered": 103106,
      "NewRecovered": "",
      "ActiveCases": 6489,
      "Serious,Critical": 2263,
      "Tot Cases/1M pop": 3139,
      "Deaths/1M pop": 237,
      "TotalTests": 4319172,
      "Tests/1M pop": 114339,
      "WHO Region": "Americas"
    },
    {
      "Country/Region": "Qatar",
      "Continent": "Asia",
      "Population": 2807805,
      "TotalCases": 112092,
      "NewCases": "",
      "TotalDeaths": 178,
      "NewDeaths": "",
      "TotalRecovered": 108831,
      "NewRecovered": "",
      "ActiveCases": 3083,
      "Serious,Critical": 77,
      "Tot Cases/1M pop": 39922,
      "Deaths/1M pop": 63,
      "TotalTests": 511000,
      "Tests/1M pop": 181993,
      "WHO Region": "EasternMediterranean"
    },
    {
      "Country/Region": "Kazakhstan",
      "Continent": "Asia",
      "Population": 18798667,
      "TotalCases": 95942,
      "NewCases": "",
      "TotalDeaths": 1058,
      "NewDeaths": "",
      "TotalRecovered": 68871,
      "NewRecovered": "",
      "ActiveCases": 26013,
      "Serious,Critical": 221,
      "Tot Cases/1M pop": 5104,
      "Deaths/1M pop": 56,
      "TotalTests": 2163713,
      "Tests/1M pop": 115099,
      "WHO Region": "Europe"
    },
    {
      "Country/Region": "Egypt",
      "Continent": "Africa",
      "Population": 102516525,
      "TotalCases": 95006,
      "NewCases": "",
      "TotalDeaths": 4951,
      "NewDeaths": "",
      "TotalRecovered": 48898,
      "NewRecovered": "",
      "ActiveCases": 41157,
      "Serious,Critical": 41,
      "Tot Cases/1M pop": 927,
      "Deaths/1M pop": 48,
      "TotalTests": 135000,
      "Tests/1M pop": 1317,
      "WHO Region": "EasternMediterranean"
    },
    {
      "Country/Region": "Ecuador",
      "Continent": "South America",
      "Population": 17668824,
      "TotalCases": 90537,
      "NewCases": "",
      "TotalDeaths": 5877,
      "NewDeaths": "",
      "TotalRecovered": 71318,
      "NewRecovered": "",
      "ActiveCases": 13342,
      "Serious,Critical": 378,
      "Tot Cases/1M pop": 5124,
      "Deaths/1M pop": 333,
      "TotalTests": 258582,
      "Tests/1M pop": 14635,
      "WHO Region": "Americas"
    },
    {
      "Country/Region": "Bolivia",
      "Continent": "South America",
      "Population": 11688459,
      "TotalCases": 86423,
      "NewCases": 1282,
      "TotalDeaths": 3465,
      "NewDeaths": 80,
      "TotalRecovered": 27373,
      "NewRecovered": 936,
      "ActiveCases": 55585,
      "Serious,Critical": 71,
      "Tot Cases/1M pop": 7394,
      "Deaths/1M pop": 296,
      "TotalTests": 183583,
      "Tests/1M pop": 15706,
      "WHO Region": "Americas"
    },
    {
      "Country/Region": "Sweden",
      "Continent": "Europe",
      "Population": 10105596,
      "TotalCases": 81967,
      "NewCases": "",
      "TotalDeaths": 5766,
      "NewDeaths": "",
      "TotalRecovered": "",
      "NewRecovered": "",
      "ActiveCases": "",
      "Serious,Critical": 38,
      "Tot Cases/1M pop": 8111,
      "Deaths/1M pop": 571,
      "TotalTests": 863315,
      "Tests/1M pop": 85429,
      "WHO Region": "Europe"
    },
    {
      "Country/Region": "Oman",
      "Continent": "Asia",
      "Population": 5118446,
      "TotalCases": 80713,
      "NewCases": "",
      "TotalDeaths": 492,
      "NewDeaths": "",
      "TotalRecovered": 70910,
      "NewRecovered": "",
      "ActiveCases": 9311,
      "Serious,Critical": 177,
      "Tot Cases/1M pop": 15769,
      "Deaths/1M pop": 96,
      "TotalTests": 309212,
      "Tests/1M pop": 60411,
      "WHO Region": "EasternMediterranean"
    },
    {
      "Country/Region": "Israel",
      "Continent": "Asia",
      "Population": 9197590,
      "TotalCases": 79559,
      "NewCases": "",
      "TotalDeaths": 576,
      "NewDeaths": "",
      "TotalRecovered": 53427,
      "NewRecovered": "",
      "ActiveCases": 25556,
      "Serious,Critical": 358,
      "Tot Cases/1M pop": 8650,
      "Deaths/1M pop": 63,
      "TotalTests": 1872453,
      "Tests/1M pop": 203581,
      "WHO Region": "Europe"
    },
    {
      "Country/Region": "Ukraine",
      "Continent": "Europe",
      "Population": 43705858,
      "TotalCases": 76808,
      "NewCases": "",
      "TotalDeaths": 1819,
      "NewDeaths": "",
      "TotalRecovered": 42524,
      "NewRecovered": "",
      "ActiveCases": 32465,
      "Serious,Critical": 158,
      "Tot Cases/1M pop": 1757,
      "Deaths/1M pop": 42,
      "TotalTests": 1116641,
      "Tests/1M pop": 25549,
      "WHO Region": "Europe"
    },
    {
      "Country/Region": "Dominican Republic",
      "Continent": "North America",
      "Population": 10858648,
      "TotalCases": 76536,
      "NewCases": "",
      "TotalDeaths": 1246,
      "NewDeaths": "",
      "TotalRecovered": 40539,
      "NewRecovered": "",
      "ActiveCases": 34751,
      "Serious,Critical": 317,
      "Tot Cases/1M pop": 7048,
      "Deaths/1M pop": 115,
      "TotalTests": 281926,
      "Tests/1M pop": 25963,
      "WHO Region": "Americas"
    },
    {
      "Country/Region": "Panama",
      "Continent": "North America",
      "Population": 4321282,
      "TotalCases": 71418,
      "NewCases": "",
      "TotalDeaths": 1574,
      "NewDeaths": "",
      "TotalRecovered": 45658,
      "NewRecovered": "",
      "ActiveCases": 24186,
      "Serious,Critical": 161,
      "Tot Cases/1M pop": 16527,
      "Deaths/1M pop": 364,
      "TotalTests": 240995,
      "Tests/1M pop": 55769,
      "WHO Region": "Americas"
    },
    {
      "Country/Region": "Belgium",
      "Continent": "Europe",
      "Population": 11594739,
      "TotalCases": 71158,
      "NewCases": "",
      "TotalDeaths": 9859,
      "NewDeaths": "",
      "TotalRecovered": 17661,
      "NewRecovered": "",
      "ActiveCases": 43638,
      "Serious,Critical": 61,
      "Tot Cases/1M pop": 6137,
      "Deaths/1M pop": 850,
      "TotalTests": 1767120,
      "Tests/1M pop": 152407,
      "WHO Region": "Europe"
    },
    {
      "Country/Region": "Kuwait",
      "Continent": "Asia",
      "Population": 4276658,
      "TotalCases": 70045,
      "NewCases": "",
      "TotalDeaths": 469,
      "NewDeaths": "",
      "TotalRecovered": 61610,
      "NewRecovered": "",
      "ActiveCases": 7966,
      "Serious,Critical": 127,
      "Tot Cases/1M pop": 16378,
      "Deaths/1M pop": 110,
      "TotalTests": 522200,
      "Tests/1M pop": 122105,
      "WHO Region": "EasternMediterranean"
    },
    {
      "Country/Region": "Belarus",
      "Continent": "Europe",
      "Population": 9449001,
      "TotalCases": 68503,
      "NewCases": "",
      "TotalDeaths": 580,
      "NewDeaths": "",
      "TotalRecovered": 63756,
      "NewRecovered": "",
      "ActiveCases": 4167,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 7250,
      "Deaths/1M pop": 61,
      "TotalTests": 1344303,
      "Tests/1M pop": 142269,
      "WHO Region": "Europe"
    },
    {
      "Country/Region": "UAE",
      "Continent": "Asia",
      "Population": 9902079,
      "TotalCases": 61845,
      "NewCases": "",
      "TotalDeaths": 354,
      "NewDeaths": "",
      "TotalRecovered": 55739,
      "NewRecovered": "",
      "ActiveCases": 5752,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 6246,
      "Deaths/1M pop": 36,
      "TotalTests": 5262658,
      "Tests/1M pop": 531470,
      "WHO Region": "EasternMediterranean"
    },
    {
      "Country/Region": "Romania",
      "Continent": "Europe",
      "Population": 19224023,
      "TotalCases": 57895,
      "NewCases": "",
      "TotalDeaths": 2566,
      "NewDeaths": "",
      "TotalRecovered": 28992,
      "NewRecovered": "",
      "ActiveCases": 26337,
      "Serious,Critical": 458,
      "Tot Cases/1M pop": 3012,
      "Deaths/1M pop": 133,
      "TotalTests": 1319369,
      "Tests/1M pop": 68631,
      "WHO Region": "Europe"
    },
    {
      "Country/Region": "Netherlands",
      "Continent": "Europe",
      "Population": 17138756,
      "TotalCases": 56982,
      "NewCases": "",
      "TotalDeaths": 6153,
      "NewDeaths": "",
      "TotalRecovered": "",
      "NewRecovered": "",
      "ActiveCases": "",
      "Serious,Critical": 37,
      "Tot Cases/1M pop": 3325,
      "Deaths/1M pop": 359,
      "TotalTests": 1079860,
      "Tests/1M pop": 63007,
      "WHO Region": "Europe"
    },
    {
      "Country/Region": "Singapore",
      "Continent": "Asia",
      "Population": 5854932,
      "TotalCases": 54555,
      "NewCases": "",
      "TotalDeaths": 27,
      "NewDeaths": "",
      "TotalRecovered": 48031,
      "NewRecovered": "",
      "ActiveCases": 6497,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 9318,
      "Deaths/1M pop": 5,
      "TotalTests": 1474372,
      "Tests/1M pop": 251817,
      "WHO Region": "WesternPacific"
    },
    {
      "Country/Region": "Guatemala",
      "Continent": "North America",
      "Population": 17946899,
      "TotalCases": 54339,
      "NewCases": "",
      "TotalDeaths": 2119,
      "NewDeaths": "",
      "TotalRecovered": 42070,
      "NewRecovered": "",
      "ActiveCases": 10150,
      "Serious,Critical": 5,
      "Tot Cases/1M pop": 3028,
      "Deaths/1M pop": 118,
      "TotalTests": 172712,
      "Tests/1M pop": 9624,
      "WHO Region": "Americas"
    },
    {
      "Country/Region": "Portugal",
      "Continent": "Europe",
      "Population": 10193593,
      "TotalCases": 52061,
      "NewCases": "",
      "TotalDeaths": 1743,
      "NewDeaths": "",
      "TotalRecovered": 37840,
      "NewRecovered": "",
      "ActiveCases": 12478,
      "Serious,Critical": 42,
      "Tot Cases/1M pop": 5107,
      "Deaths/1M pop": 171,
      "TotalTests": 1705474,
      "Tests/1M pop": 167308,
      "WHO Region": "Europe"
    },
    {
      "Country/Region": "Poland",
      "Continent": "Europe",
      "Population": 37842302,
      "TotalCases": 49515,
      "NewCases": "",
      "TotalDeaths": 1774,
      "NewDeaths": "",
      "TotalRecovered": 35642,
      "NewRecovered": "",
      "ActiveCases": 12099,
      "Serious,Critical": 72,
      "Tot Cases/1M pop": 1308,
      "Deaths/1M pop": 47,
      "TotalTests": 2374686,
      "Tests/1M pop": 62752,
      "WHO Region": "Europe"
    },
    {
      "Country/Region": "Nigeria",
      "Continent": "Africa",
      "Population": 206606300,
      "TotalCases": 45244,
      "NewCases": "",
      "TotalDeaths": 930,
      "NewDeaths": "",
      "TotalRecovered": 32430,
      "NewRecovered": "",
      "ActiveCases": 11884,
      "Serious,Critical": 7,
      "Tot Cases/1M pop": 219,
      "Deaths/1M pop": 5,
      "TotalTests": 306894,
      "Tests/1M pop": 1485,
      "WHO Region": "Africa"
    },
    {
      "Country/Region": "Honduras",
      "Continent": "North America",
      "Population": 9919704,
      "TotalCases": 45098,
      "NewCases": "",
      "TotalDeaths": 1423,
      "NewDeaths": "",
      "TotalRecovered": 6116,
      "NewRecovered": "",
      "ActiveCases": 37559,
      "Serious,Critical": 52,
      "Tot Cases/1M pop": 4546,
      "Deaths/1M pop": 143,
      "TotalTests": 109292,
      "Tests/1M pop": 11018,
      "WHO Region": "Americas"
    },
    {
      "Country/Region": "Bahrain",
      "Continent": "Asia",
      "Population": 1706669,
      "TotalCases": 42889,
      "NewCases": "",
      "TotalDeaths": 156,
      "NewDeaths": "",
      "TotalRecovered": 39945,
      "NewRecovered": "",
      "ActiveCases": 2788,
      "Serious,Critical": 41,
      "Tot Cases/1M pop": 25130,
      "Deaths/1M pop": 91,
      "TotalTests": 876700,
      "Tests/1M pop": 513691,
      "WHO Region": "EasternMediterranean"
    },
    {
      "Country/Region": "Japan",
      "Continent": "Asia",
      "Population": 126435859,
      "TotalCases": 42263,
      "NewCases": "",
      "TotalDeaths": 1026,
      "NewDeaths": "",
      "TotalRecovered": 28877,
      "NewRecovered": "",
      "ActiveCases": 12360,
      "Serious,Critical": 115,
      "Tot Cases/1M pop": 334,
      "Deaths/1M pop": 8,
      "TotalTests": 938739,
      "Tests/1M pop": 7425,
      "WHO Region": "WesternPacific"
    },
    {
      "Country/Region": "Armenia",
      "Continent": "Asia",
      "Population": 2963811,
      "TotalCases": 39819,
      "NewCases": "",
      "TotalDeaths": 772,
      "NewDeaths": "",
      "TotalRecovered": 31556,
      "NewRecovered": "",
      "ActiveCases": 7491,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 13435,
      "Deaths/1M pop": 260,
      "TotalTests": 171600,
      "Tests/1M pop": 57898,
      "WHO Region": "Europe"
    },
    {
      "Country/Region": "Ghana",
      "Continent": "Africa",
      "Population": 31133483,
      "TotalCases": 39642,
      "NewCases": "",
      "TotalDeaths": 199,
      "NewDeaths": "",
      "TotalRecovered": 36384,
      "NewRecovered": "",
      "ActiveCases": 3059,
      "Serious,Critical": 7,
      "Tot Cases/1M pop": 1273,
      "Deaths/1M pop": 6,
      "TotalTests": 405817,
      "Tests/1M pop": 13035,
      "WHO Region": "Africa"
    },
    {
      "Country/Region": "Kyrgyzstan",
      "Continent": "Asia",
      "Population": 6534479,
      "TotalCases": 38659,
      "NewCases": "",
      "TotalDeaths": 1447,
      "NewDeaths": "",
      "TotalRecovered": 30099,
      "NewRecovered": "",
      "ActiveCases": 7113,
      "Serious,Critical": 24,
      "Tot Cases/1M pop": 5916,
      "Deaths/1M pop": 221,
      "TotalTests": 267718,
      "Tests/1M pop": 40970,
      "WHO Region": "Europe"
    },
    {
      "Country/Region": "Afghanistan",
      "Continent": "Asia",
      "Population": 39009447,
      "TotalCases": 36896,
      "NewCases": "",
      "TotalDeaths": 1298,
      "NewDeaths": "",
      "TotalRecovered": 25840,
      "NewRecovered": "",
      "ActiveCases": 9758,
      "Serious,Critical": 31,
      "Tot Cases/1M pop": 946,
      "Deaths/1M pop": 33,
      "TotalTests": 90396,
      "Tests/1M pop": 2317,
      "WHO Region": "EasternMediterranean"
    },
    {
      "Country/Region": "Switzerland",
      "Continent": "Europe",
      "Population": 8660952,
      "TotalCases": 36108,
      "NewCases": "",
      "TotalDeaths": 1985,
      "NewDeaths": "",
      "TotalRecovered": 31600,
      "NewRecovered": "",
      "ActiveCases": 2523,
      "Serious,Critical": 23,
      "Tot Cases/1M pop": 4169,
      "Deaths/1M pop": 229,
      "TotalTests": 822764,
      "Tests/1M pop": 94997,
      "WHO Region": "Europe"
    },
    {
      "Country/Region": "Algeria",
      "Continent": "Africa",
      "Population": 43926079,
      "TotalCases": 33626,
      "NewCases": "",
      "TotalDeaths": 1273,
      "NewDeaths": "",
      "TotalRecovered": 23238,
      "NewRecovered": "",
      "ActiveCases": 9115,
      "Serious,Critical": 57,
      "Tot Cases/1M pop": 766,
      "Deaths/1M pop": 29,
      "TotalTests": "",
      "Tests/1M pop": "",
      "WHO Region": "Africa"
    },
    {
      "Country/Region": "Azerbaijan",
      "Continent": "Asia",
      "Population": 10148243,
      "TotalCases": 33247,
      "NewCases": "",
      "TotalDeaths": 479,
      "NewDeaths": "",
      "TotalRecovered": 29275,
      "NewRecovered": "",
      "ActiveCases": 3493,
      "Serious,Critical": 66,
      "Tot Cases/1M pop": 3276,
      "Deaths/1M pop": 47,
      "TotalTests": 766179,
      "Tests/1M pop": 75499,
      "WHO Region": "Europe"
    },
    {
      "Country/Region": "Morocco",
      "Continent": "Africa",
      "Population": 36953359,
      "TotalCases": 29644,
      "NewCases": "",
      "TotalDeaths": 449,
      "NewDeaths": "",
      "TotalRecovered": 20553,
      "NewRecovered": "",
      "ActiveCases": 8642,
      "Serious,Critical": 31,
      "Tot Cases/1M pop": 802,
      "Deaths/1M pop": 12,
      "TotalTests": 1383816,
      "Tests/1M pop": 37448,
      "WHO Region": "EasternMediterranean"
    },
    {
      "Country/Region": "Uzbekistan",
      "Continent": "Asia",
      "Population": 33516027,
      "TotalCases": 28315,
      "NewCases": "",
      "TotalDeaths": 175,
      "NewDeaths": "",
      "TotalRecovered": 19291,
      "NewRecovered": "",
      "ActiveCases": 8849,
      "Serious,Critical": 228,
      "Tot Cases/1M pop": 845,
      "Deaths/1M pop": 5,
      "TotalTests": 1377915,
      "Tests/1M pop": 41112,
      "WHO Region": "Europe"
    },
    {
      "Country/Region": "Serbia",
      "Continent": "Europe",
      "Population": 8733665,
      "TotalCases": 27332,
      "NewCases": "",
      "TotalDeaths": 621,
      "NewDeaths": "",
      "TotalRecovered": 14047,
      "NewRecovered": "",
      "ActiveCases": 12664,
      "Serious,Critical": 120,
      "Tot Cases/1M pop": 3129,
      "Deaths/1M pop": 71,
      "TotalTests": 723137,
      "Tests/1M pop": 82799,
      "WHO Region": "Europe"
    },
    {
      "Country/Region": "Moldova",
      "Continent": "Europe",
      "Population": 4032983,
      "TotalCases": 26628,
      "NewCases": "",
      "TotalDeaths": 828,
      "NewDeaths": "",
      "TotalRecovered": 18676,
      "NewRecovered": "",
      "ActiveCases": 7124,
      "Serious,Critical": 362,
      "Tot Cases/1M pop": 6603,
      "Deaths/1M pop": 205,
      "TotalTests": 128076,
      "Tests/1M pop": 31757,
      "WHO Region": "Europe"
    },
    {
      "Country/Region": "Ireland",
      "Continent": "Europe",
      "Population": 4943200,
      "TotalCases": 26372,
      "NewCases": "",
      "TotalDeaths": 1768,
      "NewDeaths": "",
      "TotalRecovered": 23364,
      "NewRecovered": "",
      "ActiveCases": 1240,
      "Serious,Critical": 5,
      "Tot Cases/1M pop": 5335,
      "Deaths/1M pop": 358,
      "TotalTests": 652917,
      "Tests/1M pop": 132084,
      "WHO Region": "Europe"
    },
    {
      "Country/Region": "Kenya",
      "Continent": "Africa",
      "Population": 53881160,
      "TotalCases": 24411,
      "NewCases": "",
      "TotalDeaths": 399,
      "NewDeaths": "",
      "TotalRecovered": 10444,
      "NewRecovered": "",
      "ActiveCases": 13568,
      "Serious,Critical": 44,
      "Tot Cases/1M pop": 453,
      "Deaths/1M pop": 7,
      "TotalTests": 335318,
      "Tests/1M pop": 6223,
      "WHO Region": "Africa"
    },
    {
      "Country/Region": "Venezuela",
      "Continent": "South America",
      "Population": 28427499,
      "TotalCases": 22299,
      "NewCases": "",
      "TotalDeaths": 195,
      "NewDeaths": "",
      "TotalRecovered": 12146,
      "NewRecovered": "",
      "ActiveCases": 9958,
      "Serious,Critical": 42,
      "Tot Cases/1M pop": 784,
      "Deaths/1M pop": 7,
      "TotalTests": 1567431,
      "Tests/1M pop": 55138,
      "WHO Region": "Americas"
    },
    {
      "Country/Region": "Nepal",
      "Continent": "Asia",
      "Population": 29186486,
      "TotalCases": 21750,
      "NewCases": "",
      "TotalDeaths": 65,
      "NewDeaths": "",
      "TotalRecovered": 15389,
      "NewRecovered": "",
      "ActiveCases": 6296,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 745,
      "Deaths/1M pop": 2,
      "TotalTests": 731977,
      "Tests/1M pop": 25079,
      "WHO Region": "South-EastAsia"
    },
    {
      "Country/Region": "Austria",
      "Continent": "Europe",
      "Population": 9011577,
      "TotalCases": 21696,
      "NewCases": "",
      "TotalDeaths": 719,
      "NewDeaths": "",
      "TotalRecovered": 19596,
      "NewRecovered": "",
      "ActiveCases": 1381,
      "Serious,Critical": 25,
      "Tot Cases/1M pop": 2408,
      "Deaths/1M pop": 80,
      "TotalTests": 937275,
      "Tests/1M pop": 104008,
      "WHO Region": "Europe"
    },
    {
      "Country/Region": "Costa Rica",
      "Continent": "North America",
      "Population": 5098730,
      "TotalCases": 21070,
      "NewCases": "",
      "TotalDeaths": 200,
      "NewDeaths": "",
      "TotalRecovered": 7038,
      "NewRecovered": "",
      "ActiveCases": 13832,
      "Serious,Critical": 103,
      "Tot Cases/1M pop": 4132,
      "Deaths/1M pop": 39,
      "TotalTests": 96110,
      "Tests/1M pop": 18850,
      "WHO Region": "Americas"
    },
    {
      "Country/Region": "Ethiopia",
      "Continent": "Africa",
      "Population": 115223736,
      "TotalCases": 20900,
      "NewCases": "",
      "TotalDeaths": 365,
      "NewDeaths": "",
      "TotalRecovered": 9027,
      "NewRecovered": "",
      "ActiveCases": 11508,
      "Serious,Critical": 185,
      "Tot Cases/1M pop": 181,
      "Deaths/1M pop": 3,
      "TotalTests": 468814,
      "Tests/1M pop": 4069,
      "WHO Region": "Africa"
    },
    {
      "Country/Region": "Australia",
      "Continent": "Australia/Oceania",
      "Population": 25528864,
      "TotalCases": 19890,
      "NewCases": "",
      "TotalDeaths": 255,
      "NewDeaths": "",
      "TotalRecovered": 10941,
      "NewRecovered": "",
      "ActiveCases": 8694,
      "Serious,Critical": 52,
      "Tot Cases/1M pop": 779,
      "Deaths/1M pop": 10,
      "TotalTests": 4631419,
      "Tests/1M pop": 181419,
      "WHO Region": "WesternPacific"
    },
    {
      "Country/Region": "El Salvador",
      "Continent": "North America",
      "Population": 6489514,
      "TotalCases": 19126,
      "NewCases": "",
      "TotalDeaths": 513,
      "NewDeaths": "",
      "TotalRecovered": 9236,
      "NewRecovered": "",
      "ActiveCases": 9377,
      "Serious,Critical": 509,
      "Tot Cases/1M pop": 2947,
      "Deaths/1M pop": 79,
      "TotalTests": 251271,
      "Tests/1M pop": 38720,
      "WHO Region": "Americas"
    },
    {
      "Country/Region": "Czechia",
      "Continent": "Europe",
      "Population": 10711019,
      "TotalCases": 17731,
      "NewCases": "",
      "TotalDeaths": 390,
      "NewDeaths": "",
      "TotalRecovered": 12320,
      "NewRecovered": "",
      "ActiveCases": 5021,
      "Serious,Critical": 17,
      "Tot Cases/1M pop": 1655,
      "Deaths/1M pop": 36,
      "TotalTests": 728670,
      "Tests/1M pop": 68030,
      "WHO Region": "Europe"
    },
    {
      "Country/Region": "Cameroon",
      "Continent": "Africa",
      "Population": 26606188,
      "TotalCases": 17718,
      "NewCases": "",
      "TotalDeaths": 391,
      "NewDeaths": "",
      "TotalRecovered": 15320,
      "NewRecovered": "",
      "ActiveCases": 2007,
      "Serious,Critical": 30,
      "Tot Cases/1M pop": 666,
      "Deaths/1M pop": 15,
      "TotalTests": 149000,
      "Tests/1M pop": 5600,
      "WHO Region": "Africa"
    },
    {
      "Country/Region": "Ivory Coast",
      "Continent": "Africa",
      "Population": 26437950,
      "TotalCases": 16447,
      "NewCases": "",
      "TotalDeaths": 103,
      "NewDeaths": "",
      "TotalRecovered": 12484,
      "NewRecovered": "",
      "ActiveCases": 3860,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 622,
      "Deaths/1M pop": 4,
      "TotalTests": 104584,
      "Tests/1M pop": 3956,
      "WHO Region": "Africa"
    },
    {
      "Country/Region": "S. Korea",
      "Continent": "Asia",
      "Population": 51273732,
      "TotalCases": 14519,
      "NewCases": 20,
      "TotalDeaths": 303,
      "NewDeaths": 1,
      "TotalRecovered": 13543,
      "NewRecovered": 42,
      "ActiveCases": 673,
      "Serious,Critical": 18,
      "Tot Cases/1M pop": 283,
      "Deaths/1M pop": 6,
      "TotalTests": 1613652,
      "Tests/1M pop": 31471,
      "WHO Region": "WesternPacific"
    },
    {
      "Country/Region": "Denmark",
      "Continent": "Europe",
      "Population": 5794279,
      "TotalCases": 14306,
      "NewCases": "",
      "TotalDeaths": 617,
      "NewDeaths": "",
      "TotalRecovered": 12787,
      "NewRecovered": "",
      "ActiveCases": 902,
      "Serious,Critical": 2,
      "Tot Cases/1M pop": 2469,
      "Deaths/1M pop": 106,
      "TotalTests": 1654512,
      "Tests/1M pop": 285542,
      "WHO Region": "Europe"
    },
    {
      "Country/Region": "Palestine",
      "Continent": "Asia",
      "Population": 5112340,
      "TotalCases": 13398,
      "NewCases": "",
      "TotalDeaths": 92,
      "NewDeaths": "",
      "TotalRecovered": 6907,
      "NewRecovered": "",
      "ActiveCases": 6399,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 2621,
      "Deaths/1M pop": 18,
      "TotalTests": 200280,
      "Tests/1M pop": 39176,
      "WHO Region": "EasternMediterranean"
    },
    {
      "Country/Region": "Bosnia and Herzegovina",
      "Continent": "Europe",
      "Population": 3278650,
      "TotalCases": 13396,
      "NewCases": "",
      "TotalDeaths": 384,
      "NewDeaths": "",
      "TotalRecovered": 7042,
      "NewRecovered": "",
      "ActiveCases": 5970,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 4086,
      "Deaths/1M pop": 117,
      "TotalTests": 147021,
      "Tests/1M pop": 44842,
      "WHO Region": "Europe"
    },
    {
      "Country/Region": "Bulgaria",
      "Continent": "Europe",
      "Population": 6942854,
      "TotalCases": 13014,
      "NewCases": "",
      "TotalDeaths": 435,
      "NewDeaths": "",
      "TotalRecovered": 7374,
      "NewRecovered": "",
      "ActiveCases": 5205,
      "Serious,Critical": 47,
      "Tot Cases/1M pop": 1874,
      "Deaths/1M pop": 63,
      "TotalTests": 294087,
      "Tests/1M pop": 42358,
      "WHO Region": "Europe"
    },
    {
      "Country/Region": "Madagascar",
      "Continent": "Africa",
      "Population": 27755708,
      "TotalCases": 12526,
      "NewCases": "",
      "TotalDeaths": 134,
      "NewDeaths": "",
      "TotalRecovered": 10148,
      "NewRecovered": "",
      "ActiveCases": 2244,
      "Serious,Critical": 88,
      "Tot Cases/1M pop": 451,
      "Deaths/1M pop": 5,
      "TotalTests": 46301,
      "Tests/1M pop": 1668,
      "WHO Region": "Africa"
    },
    {
      "Country/Region": "Sudan",
      "Continent": "Africa",
      "Population": 43943536,
      "TotalCases": 11780,
      "NewCases": "",
      "TotalDeaths": 763,
      "NewDeaths": "",
      "TotalRecovered": 6194,
      "NewRecovered": "",
      "ActiveCases": 4823,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 268,
      "Deaths/1M pop": 17,
      "TotalTests": 401,
      "Tests/1M pop": 9,
      "WHO Region": "EasternMediterranean"
    },
    {
      "Country/Region": "North Macedonia",
      "Continent": "Europe",
      "Population": 2083365,
      "TotalCases": 11399,
      "NewCases": "",
      "TotalDeaths": 517,
      "NewDeaths": "",
      "TotalRecovered": 7480,
      "NewRecovered": "",
      "ActiveCases": 3402,
      "Serious,Critical": 3,
      "Tot Cases/1M pop": 5471,
      "Deaths/1M pop": 248,
      "TotalTests": 109946,
      "Tests/1M pop": 52773,
      "WHO Region": "Europe"
    },
    {
      "Country/Region": "Senegal",
      "Continent": "Africa",
      "Population": 16783877,
      "TotalCases": 10715,
      "NewCases": "",
      "TotalDeaths": 223,
      "NewDeaths": "",
      "TotalRecovered": 7101,
      "NewRecovered": "",
      "ActiveCases": 3391,
      "Serious,Critical": 33,
      "Tot Cases/1M pop": 638,
      "Deaths/1M pop": 13,
      "TotalTests": 114761,
      "Tests/1M pop": 6838,
      "WHO Region": "Africa"
    },
    {
      "Country/Region": "Norway",
      "Continent": "Europe",
      "Population": 5425471,
      "TotalCases": 9468,
      "NewCases": "",
      "TotalDeaths": 256,
      "NewDeaths": "",
      "TotalRecovered": 8857,
      "NewRecovered": "",
      "ActiveCases": 355,
      "Serious,Critical": 3,
      "Tot Cases/1M pop": 1745,
      "Deaths/1M pop": 47,
      "TotalTests": 472841,
      "Tests/1M pop": 87152,
      "WHO Region": "Europe"
    },
    {
      "Country/Region": "DRC",
      "Continent": "Africa",
      "Population": 89802183,
      "TotalCases": 9309,
      "NewCases": "",
      "TotalDeaths": 215,
      "NewDeaths": "",
      "TotalRecovered": 8048,
      "NewRecovered": "",
      "ActiveCases": 1046,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 104,
      "Deaths/1M pop": 2,
      "TotalTests": "",
      "Tests/1M pop": "",
      "WHO Region": "Africa"
    },
    {
      "Country/Region": "Malaysia",
      "Continent": "Asia",
      "Population": 32406372,
      "TotalCases": 9038,
      "NewCases": "",
      "TotalDeaths": 125,
      "NewDeaths": "",
      "TotalRecovered": 8713,
      "NewRecovered": "",
      "ActiveCases": 200,
      "Serious,Critical": 2,
      "Tot Cases/1M pop": 279,
      "Deaths/1M pop": 4,
      "TotalTests": 991333,
      "Tests/1M pop": 30591,
      "WHO Region": "WesternPacific"
    },
    {
      "Country/Region": "French Guiana",
      "Continent": "South America",
      "Population": 299385,
      "TotalCases": 8127,
      "NewCases": "",
      "TotalDeaths": 47,
      "NewDeaths": "",
      "TotalRecovered": 7240,
      "NewRecovered": "",
      "ActiveCases": 840,
      "Serious,Critical": 23,
      "Tot Cases/1M pop": 27146,
      "Deaths/1M pop": 157,
      "TotalTests": 41412,
      "Tests/1M pop": 138324,
      "WHO Region": ""
    },
    {
      "Country/Region": "Gabon",
      "Continent": "Africa",
      "Population": 2230563,
      "TotalCases": 7787,
      "NewCases": "",
      "TotalDeaths": 51,
      "NewDeaths": "",
      "TotalRecovered": 5609,
      "NewRecovered": "",
      "ActiveCases": 2127,
      "Serious,Critical": 11,
      "Tot Cases/1M pop": 3491,
      "Deaths/1M pop": 23,
      "TotalTests": 85369,
      "Tests/1M pop": 38272,
      "WHO Region": "Africa"
    },
    {
      "Country/Region": "Tajikistan",
      "Continent": "Asia",
      "Population": 9557468,
      "TotalCases": 7665,
      "NewCases": "",
      "TotalDeaths": 62,
      "NewDeaths": "",
      "TotalRecovered": 6443,
      "NewRecovered": "",
      "ActiveCases": 1160,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 802,
      "Deaths/1M pop": 6,
      "TotalTests": "",
      "Tests/1M pop": "",
      "WHO Region": "Europe"
    },
    {
      "Country/Region": "Guinea",
      "Continent": "Africa",
      "Population": 13164905,
      "TotalCases": 7664,
      "NewCases": "",
      "TotalDeaths": 49,
      "NewDeaths": "",
      "TotalRecovered": 6757,
      "NewRecovered": "",
      "ActiveCases": 858,
      "Serious,Critical": 24,
      "Tot Cases/1M pop": 582,
      "Deaths/1M pop": 4,
      "TotalTests": 14407,
      "Tests/1M pop": 1094,
      "WHO Region": "Africa"
    },
    {
      "Country/Region": "Haiti",
      "Continent": "North America",
      "Population": 11416103,
      "TotalCases": 7544,
      "NewCases": "",
      "TotalDeaths": 171,
      "NewDeaths": "",
      "TotalRecovered": 4832,
      "NewRecovered": "",
      "ActiveCases": 2541,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 661,
      "Deaths/1M pop": 15,
      "TotalTests": 18443,
      "Tests/1M pop": 1616,
      "WHO Region": "Americas"
    },
    {
      "Country/Region": "Finland",
      "Continent": "Europe",
      "Population": 5541604,
      "TotalCases": 7532,
      "NewCases": "",
      "TotalDeaths": 331,
      "NewDeaths": "",
      "TotalRecovered": 6980,
      "NewRecovered": "",
      "ActiveCases": 221,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 1359,
      "Deaths/1M pop": 60,
      "TotalTests": 389500,
      "Tests/1M pop": 70287,
      "WHO Region": "Europe"
    },
    {
      "Country/Region": "Zambia",
      "Continent": "Africa",
      "Population": 18430129,
      "TotalCases": 7164,
      "NewCases": "",
      "TotalDeaths": 199,
      "NewDeaths": "",
      "TotalRecovered": 5786,
      "NewRecovered": "",
      "ActiveCases": 1179,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 389,
      "Deaths/1M pop": 11,
      "TotalTests": 90307,
      "Tests/1M pop": 4900,
      "WHO Region": "Africa"
    },
    {
      "Country/Region": "Luxembourg",
      "Continent": "Europe",
      "Population": 626952,
      "TotalCases": 7073,
      "NewCases": "",
      "TotalDeaths": 119,
      "NewDeaths": "",
      "TotalRecovered": 5750,
      "NewRecovered": "",
      "ActiveCases": 1204,
      "Serious,Critical": 9,
      "Tot Cases/1M pop": 11282,
      "Deaths/1M pop": 190,
      "TotalTests": 623994,
      "Tests/1M pop": 995282,
      "WHO Region": "Europe"
    },
    {
      "Country/Region": "Mauritania",
      "Continent": "Africa",
      "Population": 4660728,
      "TotalCases": 6444,
      "NewCases": "",
      "TotalDeaths": 157,
      "NewDeaths": "",
      "TotalRecovered": 5291,
      "NewRecovered": "",
      "ActiveCases": 996,
      "Serious,Critical": 3,
      "Tot Cases/1M pop": 1383,
      "Deaths/1M pop": 34,
      "TotalTests": 57387,
      "Tests/1M pop": 12313,
      "WHO Region": "Africa"
    },
    {
      "Country/Region": "Paraguay",
      "Continent": "South America",
      "Population": 7141091,
      "TotalCases": 6375,
      "NewCases": "",
      "TotalDeaths": 66,
      "NewDeaths": "",
      "TotalRecovered": 4974,
      "NewRecovered": "",
      "ActiveCases": 1335,
      "Serious,Critical": 23,
      "Tot Cases/1M pop": 893,
      "Deaths/1M pop": 9,
      "TotalTests": 135277,
      "Tests/1M pop": 18943,
      "WHO Region": "Americas"
    },
    {
      "Country/Region": "Albania",
      "Continent": "Europe",
      "Population": 2877470,
      "TotalCases": 6016,
      "NewCases": "",
      "TotalDeaths": 188,
      "NewDeaths": "",
      "TotalRecovered": 3155,
      "NewRecovered": "",
      "ActiveCases": 2673,
      "Serious,Critical": 23,
      "Tot Cases/1M pop": 2091,
      "Deaths/1M pop": 65,
      "TotalTests": 38997,
      "Tests/1M pop": 13553,
      "WHO Region": "Europe"
    },
    {
      "Country/Region": "Lebanon",
      "Continent": "Asia",
      "Population": 6822220,
      "TotalCases": 5672,
      "NewCases": "",
      "TotalDeaths": 70,
      "NewDeaths": "",
      "TotalRecovered": 1974,
      "NewRecovered": "",
      "ActiveCases": 3628,
      "Serious,Critical": 46,
      "Tot Cases/1M pop": 831,
      "Deaths/1M pop": 10,
      "TotalTests": 345268,
      "Tests/1M pop": 50609,
      "WHO Region": "EasternMediterranean"
    },
    {
      "Country/Region": "Croatia",
      "Continent": "Europe",
      "Population": 4102577,
      "TotalCases": 5404,
      "NewCases": "",
      "TotalDeaths": 155,
      "NewDeaths": "",
      "TotalRecovered": 4688,
      "NewRecovered": "",
      "ActiveCases": 561,
      "Serious,Critical": 7,
      "Tot Cases/1M pop": 1317,
      "Deaths/1M pop": 38,
      "TotalTests": 125317,
      "Tests/1M pop": 30546,
      "WHO Region": "Europe"
    },
    {
      "Country/Region": "Djibouti",
      "Continent": "Africa",
      "Population": 989387,
      "TotalCases": 5330,
      "NewCases": "",
      "TotalDeaths": 59,
      "NewDeaths": "",
      "TotalRecovered": 5057,
      "NewRecovered": "",
      "ActiveCases": 214,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 5387,
      "Deaths/1M pop": 60,
      "TotalTests": 59909,
      "Tests/1M pop": 60552,
      "WHO Region": "EasternMediterranean"
    },
    {
      "Country/Region": "Greece",
      "Continent": "Europe",
      "Population": 10417673,
      "TotalCases": 5123,
      "NewCases": "",
      "TotalDeaths": 210,
      "NewDeaths": "",
      "TotalRecovered": 1374,
      "NewRecovered": "",
      "ActiveCases": 3539,
      "Serious,Critical": 14,
      "Tot Cases/1M pop": 492,
      "Deaths/1M pop": 20,
      "TotalTests": 619393,
      "Tests/1M pop": 59456,
      "WHO Region": "Europe"
    },
    {
      "Country/Region": "Libya",
      "Continent": "Africa",
      "Population": 6880353,
      "TotalCases": 4879,
      "NewCases": "",
      "TotalDeaths": 107,
      "NewDeaths": "",
      "TotalRecovered": 652,
      "NewRecovered": "",
      "ActiveCases": 4120,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 709,
      "Deaths/1M pop": 16,
      "TotalTests": 59699,
      "Tests/1M pop": 8677,
      "WHO Region": "EasternMediterranean"
    },
    {
      "Country/Region": "Equatorial Guinea",
      "Continent": "Africa",
      "Population": 1407001,
      "TotalCases": 4821,
      "NewCases": "",
      "TotalDeaths": 83,
      "NewDeaths": "",
      "TotalRecovered": 2182,
      "NewRecovered": "",
      "ActiveCases": 2556,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 3426,
      "Deaths/1M pop": 59,
      "TotalTests": 44356,
      "Tests/1M pop": 31525,
      "WHO Region": "Africa"
    },
    {
      "Country/Region": "Maldives",
      "Continent": "Asia",
      "Population": 541448,
      "TotalCases": 4680,
      "NewCases": "",
      "TotalDeaths": 19,
      "NewDeaths": "",
      "TotalRecovered": 2725,
      "NewRecovered": "",
      "ActiveCases": 1936,
      "Serious,Critical": 12,
      "Tot Cases/1M pop": 8643,
      "Deaths/1M pop": 35,
      "TotalTests": 85587,
      "Tests/1M pop": 158071,
      "WHO Region": "South-EastAsia"
    },
    {
      "Country/Region": "CAR",
      "Continent": "Africa",
      "Population": 4837752,
      "TotalCases": 4620,
      "NewCases": "",
      "TotalDeaths": 59,
      "NewDeaths": "",
      "TotalRecovered": 1641,
      "NewRecovered": "",
      "ActiveCases": 2920,
      "Serious,Critical": 2,
      "Tot Cases/1M pop": 955,
      "Deaths/1M pop": 12,
      "TotalTests": 29589,
      "Tests/1M pop": 6116,
      "WHO Region": ""
    },
    {
      "Country/Region": "Hungary",
      "Continent": "Europe",
      "Population": 9657785,
      "TotalCases": 4597,
      "NewCases": "",
      "TotalDeaths": 600,
      "NewDeaths": "",
      "TotalRecovered": 3463,
      "NewRecovered": "",
      "ActiveCases": 534,
      "Serious,Critical": 8,
      "Tot Cases/1M pop": 476,
      "Deaths/1M pop": 62,
      "TotalTests": 352546,
      "Tests/1M pop": 36504,
      "WHO Region": "Europe"
    },
    {
      "Country/Region": "Malawi",
      "Continent": "Africa",
      "Population": 19174839,
      "TotalCases": 4491,
      "NewCases": "",
      "TotalDeaths": 137,
      "NewDeaths": "",
      "TotalRecovered": 2137,
      "NewRecovered": "",
      "ActiveCases": 2217,
      "Serious,Critical": 4,
      "Tot Cases/1M pop": 234,
      "Deaths/1M pop": 7,
      "TotalTests": 33466,
      "Tests/1M pop": 1745,
      "WHO Region": "Africa"
    },
    {
      "Country/Region": "Zimbabwe",
      "Continent": "Africa",
      "Population": 14883803,
      "TotalCases": 4339,
      "NewCases": "",
      "TotalDeaths": 84,
      "NewDeaths": "",
      "TotalRecovered": 1264,
      "NewRecovered": "",
      "ActiveCases": 2991,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 292,
      "Deaths/1M pop": 6,
      "TotalTests": 140421,
      "Tests/1M pop": 9434,
      "WHO Region": "Africa"
    },
    {
      "Country/Region": "Nicaragua",
      "Continent": "North America",
      "Population": 6632263,
      "TotalCases": 3902,
      "NewCases": "",
      "TotalDeaths": 123,
      "NewDeaths": "",
      "TotalRecovered": 2913,
      "NewRecovered": "",
      "ActiveCases": 866,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 588,
      "Deaths/1M pop": 19,
      "TotalTests": "",
      "Tests/1M pop": "",
      "WHO Region": "Americas"
    },
    {
      "Country/Region": "Hong Kong",
      "Continent": "Asia",
      "Population": 7503041,
      "TotalCases": 3850,
      "NewCases": "",
      "TotalDeaths": 46,
      "NewDeaths": "",
      "TotalRecovered": 2458,
      "NewRecovered": "",
      "ActiveCases": 1346,
      "Serious,Critical": 39,
      "Tot Cases/1M pop": 513,
      "Deaths/1M pop": 6,
      "TotalTests": 692430,
      "Tests/1M pop": 92287,
      "WHO Region": "WesternPacific"
    },
    {
      "Country/Region": "Congo",
      "Continent": "Africa",
      "Population": 5530506,
      "TotalCases": 3546,
      "NewCases": "",
      "TotalDeaths": 58,
      "NewDeaths": "",
      "TotalRecovered": 1589,
      "NewRecovered": "",
      "ActiveCases": 1899,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 641,
      "Deaths/1M pop": 10,
      "TotalTests": "",
      "Tests/1M pop": "",
      "WHO Region": "Africa"
    },
    {
      "Country/Region": "Montenegro",
      "Continent": "Europe",
      "Population": 628074,
      "TotalCases": 3480,
      "NewCases": "",
      "TotalDeaths": 60,
      "NewDeaths": "",
      "TotalRecovered": 2178,
      "NewRecovered": "",
      "ActiveCases": 1242,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 5541,
      "Deaths/1M pop": 96,
      "TotalTests": 38427,
      "Tests/1M pop": 61182,
      "WHO Region": "Europe"
    },
    {
      "Country/Region": "Thailand",
      "Continent": "Asia",
      "Population": 69817894,
      "TotalCases": 3330,
      "NewCases": "",
      "TotalDeaths": 58,
      "NewDeaths": "",
      "TotalRecovered": 3148,
      "NewRecovered": "",
      "ActiveCases": 124,
      "Serious,Critical": 1,
      "Tot Cases/1M pop": 48,
      "Deaths/1M pop": 0.8,
      "TotalTests": 749213,
      "Tests/1M pop": 10731,
      "WHO Region": "South-EastAsia"
    },
    {
      "Country/Region": "Somalia",
      "Continent": "Africa",
      "Population": 15933012,
      "TotalCases": 3227,
      "NewCases": "",
      "TotalDeaths": 93,
      "NewDeaths": "",
      "TotalRecovered": 1728,
      "NewRecovered": "",
      "ActiveCases": 1406,
      "Serious,Critical": 2,
      "Tot Cases/1M pop": 203,
      "Deaths/1M pop": 6,
      "TotalTests": "",
      "Tests/1M pop": "",
      "WHO Region": "EasternMediterranean"
    },
    {
      "Country/Region": "Mayotte",
      "Continent": "Africa",
      "Population": 273419,
      "TotalCases": 3042,
      "NewCases": "",
      "TotalDeaths": 39,
      "NewDeaths": "",
      "TotalRecovered": 2738,
      "NewRecovered": "",
      "ActiveCases": 265,
      "Serious,Critical": 2,
      "Tot Cases/1M pop": 11126,
      "Deaths/1M pop": 143,
      "TotalTests": 13000,
      "Tests/1M pop": 47546,
      "WHO Region": ""
    },
    {
      "Country/Region": "Eswatini",
      "Continent": "Africa",
      "Population": 1161348,
      "TotalCases": 2968,
      "NewCases": "",
      "TotalDeaths": 55,
      "NewDeaths": "",
      "TotalRecovered": 1476,
      "NewRecovered": "",
      "ActiveCases": 1437,
      "Serious,Critical": 5,
      "Tot Cases/1M pop": 2556,
      "Deaths/1M pop": 47,
      "TotalTests": 20784,
      "Tests/1M pop": 17896,
      "WHO Region": "Africa"
    },
    {
      "Country/Region": "Sri Lanka",
      "Continent": "Asia",
      "Population": 21422362,
      "TotalCases": 2839,
      "NewCases": "",
      "TotalDeaths": 11,
      "NewDeaths": "",
      "TotalRecovered": 2541,
      "NewRecovered": "",
      "ActiveCases": 287,
      "Serious,Critical": 1,
      "Tot Cases/1M pop": 133,
      "Deaths/1M pop": 0.5,
      "TotalTests": 166737,
      "Tests/1M pop": 7783,
      "WHO Region": "South-EastAsia"
    },
    {
      "Country/Region": "Cuba",
      "Continent": "North America",
      "Population": 11325899,
      "TotalCases": 2775,
      "NewCases": "",
      "TotalDeaths": 88,
      "NewDeaths": "",
      "TotalRecovered": 2409,
      "NewRecovered": "",
      "ActiveCases": 278,
      "Serious,Critical": 4,
      "Tot Cases/1M pop": 245,
      "Deaths/1M pop": 8,
      "TotalTests": 285471,
      "Tests/1M pop": 25205,
      "WHO Region": "Americas"
    },
    {
      "Country/Region": "Cabo Verde",
      "Continent": "Africa",
      "Population": 556581,
      "TotalCases": 2734,
      "NewCases": "",
      "TotalDeaths": 27,
      "NewDeaths": "",
      "TotalRecovered": 2010,
      "NewRecovered": "",
      "ActiveCases": 697,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 4912,
      "Deaths/1M pop": 49,
      "TotalTests": 61633,
      "Tests/1M pop": 110735,
      "WHO Region": "Africa"
    },
    {
      "Country/Region": "Namibia",
      "Continent": "Africa",
      "Population": 2545264,
      "TotalCases": 2652,
      "NewCases": "",
      "TotalDeaths": 15,
      "NewDeaths": "",
      "TotalRecovered": 563,
      "NewRecovered": "",
      "ActiveCases": 2074,
      "Serious,Critical": 24,
      "Tot Cases/1M pop": 1042,
      "Deaths/1M pop": 6,
      "TotalTests": 29233,
      "Tests/1M pop": 11485,
      "WHO Region": "Africa"
    },
    {
      "Country/Region": "Mali",
      "Continent": "Africa",
      "Population": 20302901,
      "TotalCases": 2552,
      "NewCases": "",
      "TotalDeaths": 124,
      "NewDeaths": "",
      "TotalRecovered": 1954,
      "NewRecovered": "",
      "ActiveCases": 474,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 126,
      "Deaths/1M pop": 6,
      "TotalTests": 25152,
      "Tests/1M pop": 1239,
      "WHO Region": "Africa"
    },
    {
      "Country/Region": "Slovakia",
      "Continent": "Europe",
      "Population": 5459915,
      "TotalCases": 2480,
      "NewCases": "",
      "TotalDeaths": 29,
      "NewDeaths": "",
      "TotalRecovered": 1824,
      "NewRecovered": "",
      "ActiveCases": 627,
      "Serious,Critical": 2,
      "Tot Cases/1M pop": 454,
      "Deaths/1M pop": 5,
      "TotalTests": 272322,
      "Tests/1M pop": 49877,
      "WHO Region": "Europe"
    },
    {
      "Country/Region": "South Sudan",
      "Continent": "Africa",
      "Population": 11206572,
      "TotalCases": 2450,
      "NewCases": "",
      "TotalDeaths": 47,
      "NewDeaths": "",
      "TotalRecovered": 1175,
      "NewRecovered": "",
      "ActiveCases": 1228,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 219,
      "Deaths/1M pop": 4,
      "TotalTests": 12044,
      "Tests/1M pop": 1075,
      "WHO Region": "Africa"
    },
    {
      "Country/Region": "Slovenia",
      "Continent": "Europe",
      "Population": 2078968,
      "TotalCases": 2223,
      "NewCases": "",
      "TotalDeaths": 125,
      "NewDeaths": "",
      "TotalRecovered": 1909,
      "NewRecovered": "",
      "ActiveCases": 189,
      "Serious,Critical": 2,
      "Tot Cases/1M pop": 1069,
      "Deaths/1M pop": 60,
      "TotalTests": 135702,
      "Tests/1M pop": 65274,
      "WHO Region": "Europe"
    },
    {
      "Country/Region": "Lithuania",
      "Continent": "Europe",
      "Population": 2718121,
      "TotalCases": 2171,
      "NewCases": "",
      "TotalDeaths": 81,
      "NewDeaths": "",
      "TotalRecovered": 1656,
      "NewRecovered": "",
      "ActiveCases": 434,
      "Serious,Critical": 6,
      "Tot Cases/1M pop": 799,
      "Deaths/1M pop": 30,
      "TotalTests": 540784,
      "Tests/1M pop": 198955,
      "WHO Region": "Europe"
    },
    {
      "Country/Region": "Estonia",
      "Continent": "Europe",
      "Population": 1326627,
      "TotalCases": 2124,
      "NewCases": "",
      "TotalDeaths": 63,
      "NewDeaths": "",
      "TotalRecovered": 1954,
      "NewRecovered": "",
      "ActiveCases": 107,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 1601,
      "Deaths/1M pop": 47,
      "TotalTests": 122880,
      "Tests/1M pop": 92626,
      "WHO Region": "Europe"
    },
    {
      "Country/Region": "Mozambique",
      "Continent": "Africa",
      "Population": 31333962,
      "TotalCases": 2120,
      "NewCases": "",
      "TotalDeaths": 15,
      "NewDeaths": "",
      "TotalRecovered": 795,
      "NewRecovered": "",
      "ActiveCases": 1310,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 68,
      "Deaths/1M pop": 0.5,
      "TotalTests": 65151,
      "Tests/1M pop": 2079,
      "WHO Region": "Africa"
    },
    {
      "Country/Region": "Rwanda",
      "Continent": "Africa",
      "Population": 12981546,
      "TotalCases": 2111,
      "NewCases": "",
      "TotalDeaths": 5,
      "NewDeaths": "",
      "TotalRecovered": 1258,
      "NewRecovered": "",
      "ActiveCases": 848,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 163,
      "Deaths/1M pop": 0.4,
      "TotalTests": 286251,
      "Tests/1M pop": 22051,
      "WHO Region": "Africa"
    },
    {
      "Country/Region": "Suriname",
      "Continent": "South America",
      "Population": 587154,
      "TotalCases": 2096,
      "NewCases": "",
      "TotalDeaths": 29,
      "NewDeaths": "",
      "TotalRecovered": 1446,
      "NewRecovered": "",
      "ActiveCases": 621,
      "Serious,Critical": 9,
      "Tot Cases/1M pop": 3570,
      "Deaths/1M pop": 49,
      "TotalTests": 2785,
      "Tests/1M pop": 4743,
      "WHO Region": "Americas"
    },
    {
      "Country/Region": "Guinea-Bissau",
      "Continent": "Africa",
      "Population": 1972277,
      "TotalCases": 2032,
      "NewCases": "",
      "TotalDeaths": 27,
      "NewDeaths": "",
      "TotalRecovered": 944,
      "NewRecovered": "",
      "ActiveCases": 1061,
      "Serious,Critical": 5,
      "Tot Cases/1M pop": 1030,
      "Deaths/1M pop": 14,
      "TotalTests": 1500,
      "Tests/1M pop": 761,
      "WHO Region": "Africa"
    },
    {
      "Country/Region": "Benin",
      "Continent": "Africa",
      "Population": 12151976,
      "TotalCases": 1936,
      "NewCases": "",
      "TotalDeaths": 38,
      "NewDeaths": "",
      "TotalRecovered": 1600,
      "NewRecovered": "",
      "ActiveCases": 298,
      "Serious,Critical": 1,
      "Tot Cases/1M pop": 159,
      "Deaths/1M pop": 3,
      "TotalTests": 93677,
      "Tests/1M pop": 7709,
      "WHO Region": "Africa"
    },
    {
      "Country/Region": "Iceland",
      "Continent": "Europe",
      "Population": 341465,
      "TotalCases": 1930,
      "NewCases": "",
      "TotalDeaths": 10,
      "NewDeaths": "",
      "TotalRecovered": 1825,
      "NewRecovered": "",
      "ActiveCases": 95,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 5652,
      "Deaths/1M pop": 29,
      "TotalTests": 149693,
      "Tests/1M pop": 438385,
      "WHO Region": "Europe"
    },
    {
      "Country/Region": "Sierra Leone",
      "Continent": "Africa",
      "Population": 7992169,
      "TotalCases": 1877,
      "NewCases": "",
      "TotalDeaths": 67,
      "NewDeaths": "",
      "TotalRecovered": 1427,
      "NewRecovered": "",
      "ActiveCases": 383,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 235,
      "Deaths/1M pop": 8,
      "TotalTests": "",
      "Tests/1M pop": "",
      "WHO Region": "Africa"
    },
    {
      "Country/Region": "Yemen",
      "Continent": "Asia",
      "Population": 29886897,
      "TotalCases": 1768,
      "NewCases": "",
      "TotalDeaths": 508,
      "NewDeaths": "",
      "TotalRecovered": 898,
      "NewRecovered": "",
      "ActiveCases": 362,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 59,
      "Deaths/1M pop": 17,
      "TotalTests": 120,
      "Tests/1M pop": 4,
      "WHO Region": "EasternMediterranean"
    },
    {
      "Country/Region": "Tunisia",
      "Continent": "Africa",
      "Population": 11830801,
      "TotalCases": 1642,
      "NewCases": "",
      "TotalDeaths": 51,
      "NewDeaths": "",
      "TotalRecovered": 1241,
      "NewRecovered": "",
      "ActiveCases": 350,
      "Serious,Critical": 9,
      "Tot Cases/1M pop": 139,
      "Deaths/1M pop": 4,
      "TotalTests": 100298,
      "Tests/1M pop": 8478,
      "WHO Region": "EasternMediterranean"
    },
    {
      "Country/Region": "New Zealand",
      "Continent": "Australia/Oceania",
      "Population": 5002100,
      "TotalCases": 1569,
      "NewCases": "",
      "TotalDeaths": 22,
      "NewDeaths": "",
      "TotalRecovered": 1524,
      "NewRecovered": "",
      "ActiveCases": 23,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 314,
      "Deaths/1M pop": 4,
      "TotalTests": 486943,
      "Tests/1M pop": 97348,
      "WHO Region": "WesternPacific"
    },
    {
      "Country/Region": "Angola",
      "Continent": "Africa",
      "Population": 32956300,
      "TotalCases": 1483,
      "NewCases": "",
      "TotalDeaths": 64,
      "NewDeaths": "",
      "TotalRecovered": 520,
      "NewRecovered": "",
      "ActiveCases": 899,
      "Serious,Critical": 20,
      "Tot Cases/1M pop": 45,
      "Deaths/1M pop": 2,
      "TotalTests": 64747,
      "Tests/1M pop": 1965,
      "WHO Region": "Africa"
    },
    {
      "Country/Region": "Uruguay",
      "Continent": "South America",
      "Population": 3474956,
      "TotalCases": 1318,
      "NewCases": "",
      "TotalDeaths": 37,
      "NewDeaths": "",
      "TotalRecovered": 1079,
      "NewRecovered": "",
      "ActiveCases": 202,
      "Serious,Critical": 2,
      "Tot Cases/1M pop": 379,
      "Deaths/1M pop": 11,
      "TotalTests": 126956,
      "Tests/1M pop": 36535,
      "WHO Region": "Americas"
    },
    {
      "Country/Region": "Latvia",
      "Continent": "Europe",
      "Population": 1883936,
      "TotalCases": 1275,
      "NewCases": "",
      "TotalDeaths": 32,
      "NewDeaths": "",
      "TotalRecovered": 1070,
      "NewRecovered": "",
      "ActiveCases": 173,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 677,
      "Deaths/1M pop": 17,
      "TotalTests": 207909,
      "Tests/1M pop": 110359,
      "WHO Region": "Europe"
    },
    {
      "Country/Region": "Jordan",
      "Continent": "Asia",
      "Population": 10213138,
      "TotalCases": 1232,
      "NewCases": "",
      "TotalDeaths": 11,
      "NewDeaths": "",
      "TotalRecovered": 1171,
      "NewRecovered": "",
      "ActiveCases": 50,
      "Serious,Critical": 3,
      "Tot Cases/1M pop": 121,
      "Deaths/1M pop": 1,
      "TotalTests": 628745,
      "Tests/1M pop": 61562,
      "WHO Region": "EasternMediterranean"
    },
    {
      "Country/Region": "Liberia",
      "Continent": "Africa",
      "Population": 5068618,
      "TotalCases": 1224,
      "NewCases": "",
      "TotalDeaths": 78,
      "NewDeaths": "",
      "TotalRecovered": 705,
      "NewRecovered": "",
      "ActiveCases": 441,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 241,
      "Deaths/1M pop": 15,
      "TotalTests": "",
      "Tests/1M pop": "",
      "WHO Region": "Africa"
    },
    {
      "Country/Region": "Uganda",
      "Continent": "Africa",
      "Population": 45867852,
      "TotalCases": 1223,
      "NewCases": "",
      "TotalDeaths": 5,
      "NewDeaths": "",
      "TotalRecovered": 1102,
      "NewRecovered": "",
      "ActiveCases": 116,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 27,
      "Deaths/1M pop": 0.1,
      "TotalTests": 288367,
      "Tests/1M pop": 6287,
      "WHO Region": "Africa"
    },
    {
      "Country/Region": "Cyprus",
      "Continent": "Asia",
      "Population": 1208238,
      "TotalCases": 1208,
      "NewCases": "",
      "TotalDeaths": 19,
      "NewDeaths": "",
      "TotalRecovered": 856,
      "NewRecovered": "",
      "ActiveCases": 333,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 1000,
      "Deaths/1M pop": 16,
      "TotalTests": 216597,
      "Tests/1M pop": 179267,
      "WHO Region": "Europe"
    },
    {
      "Country/Region": "Georgia",
      "Continent": "Asia",
      "Population": 3988368,
      "TotalCases": 1206,
      "NewCases": "",
      "TotalDeaths": 17,
      "NewDeaths": "",
      "TotalRecovered": 987,
      "NewRecovered": "",
      "ActiveCases": 202,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 302,
      "Deaths/1M pop": 4,
      "TotalTests": 240473,
      "Tests/1M pop": 60294,
      "WHO Region": "Europe"
    },
    {
      "Country/Region": "Burkina Faso",
      "Continent": "Africa",
      "Population": 20954852,
      "TotalCases": 1158,
      "NewCases": "",
      "TotalDeaths": 54,
      "NewDeaths": "",
      "TotalRecovered": 961,
      "NewRecovered": "",
      "ActiveCases": 143,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 55,
      "Deaths/1M pop": 3,
      "TotalTests": "",
      "Tests/1M pop": "",
      "WHO Region": "Africa"
    },
    {
      "Country/Region": "Niger",
      "Continent": "Africa",
      "Population": 24281433,
      "TotalCases": 1153,
      "NewCases": "",
      "TotalDeaths": 69,
      "NewDeaths": "",
      "TotalRecovered": 1057,
      "NewRecovered": "",
      "ActiveCases": 27,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 47,
      "Deaths/1M pop": 3,
      "TotalTests": 9052,
      "Tests/1M pop": 373,
      "WHO Region": "Africa"
    },
    {
      "Country/Region": "Togo",
      "Continent": "Africa",
      "Population": 8296582,
      "TotalCases": 1012,
      "NewCases": "",
      "TotalDeaths": 22,
      "NewDeaths": "",
      "TotalRecovered": 697,
      "NewRecovered": "",
      "ActiveCases": 293,
      "Serious,Critical": 2,
      "Tot Cases/1M pop": 122,
      "Deaths/1M pop": 3,
      "TotalTests": 45767,
      "Tests/1M pop": 5516,
      "WHO Region": "Africa"
    },
    {
      "Country/Region": "Syria",
      "Continent": "Asia",
      "Population": 17539600,
      "TotalCases": 999,
      "NewCases": "",
      "TotalDeaths": 48,
      "NewDeaths": "",
      "TotalRecovered": 311,
      "NewRecovered": "",
      "ActiveCases": 640,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 57,
      "Deaths/1M pop": 3,
      "TotalTests": "",
      "Tests/1M pop": "",
      "WHO Region": "EasternMediterranean"
    },
    {
      "Country/Region": "Jamaica",
      "Continent": "North America",
      "Population": 2962478,
      "TotalCases": 958,
      "NewCases": 30,
      "TotalDeaths": 12,
      "NewDeaths": "",
      "TotalRecovered": 745,
      "NewRecovered": "",
      "ActiveCases": 201,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 323,
      "Deaths/1M pop": 4,
      "TotalTests": 41840,
      "Tests/1M pop": 14123,
      "WHO Region": "Americas"
    },
    {
      "Country/Region": "Malta",
      "Continent": "Europe",
      "Population": 441663,
      "TotalCases": 946,
      "NewCases": "",
      "TotalDeaths": 9,
      "NewDeaths": "",
      "TotalRecovered": 670,
      "NewRecovered": "",
      "ActiveCases": 267,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 2142,
      "Deaths/1M pop": 20,
      "TotalTests": 136713,
      "Tests/1M pop": 309541,
      "WHO Region": "Europe"
    },
    {
      "Country/Region": "Andorra",
      "Continent": "Europe",
      "Population": 77278,
      "TotalCases": 944,
      "NewCases": "",
      "TotalDeaths": 52,
      "NewDeaths": "",
      "TotalRecovered": 828,
      "NewRecovered": "",
      "ActiveCases": 64,
      "Serious,Critical": 1,
      "Tot Cases/1M pop": 12216,
      "Deaths/1M pop": 673,
      "TotalTests": 3750,
      "Tests/1M pop": 48526,
      "WHO Region": "Europe"
    },
    {
      "Country/Region": "Chad",
      "Continent": "Africa",
      "Population": 16467965,
      "TotalCases": 942,
      "NewCases": "",
      "TotalDeaths": 76,
      "NewDeaths": "",
      "TotalRecovered": 838,
      "NewRecovered": "",
      "ActiveCases": 28,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 57,
      "Deaths/1M pop": 5,
      "TotalTests": "",
      "Tests/1M pop": "",
      "WHO Region": "Africa"
    },
    {
      "Country/Region": "Gambia",
      "Continent": "Africa",
      "Population": 2422754,
      "TotalCases": 935,
      "NewCases": "",
      "TotalDeaths": 16,
      "NewDeaths": "",
      "TotalRecovered": 136,
      "NewRecovered": "",
      "ActiveCases": 783,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 386,
      "Deaths/1M pop": 7,
      "TotalTests": 5183,
      "Tests/1M pop": 2139,
      "WHO Region": "Africa"
    },
    {
      "Country/Region": "Sao Tome and Principe",
      "Continent": "Africa",
      "Population": 219544,
      "TotalCases": 878,
      "NewCases": "",
      "TotalDeaths": 15,
      "NewDeaths": "",
      "TotalRecovered": 797,
      "NewRecovered": "",
      "ActiveCases": 66,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 3999,
      "Deaths/1M pop": 68,
      "TotalTests": 3079,
      "Tests/1M pop": 14025,
      "WHO Region": "Africa"
    },
    {
      "Country/Region": "Botswana",
      "Continent": "Africa",
      "Population": 2356075,
      "TotalCases": 804,
      "NewCases": "",
      "TotalDeaths": 2,
      "NewDeaths": "",
      "TotalRecovered": 63,
      "NewRecovered": "",
      "ActiveCases": 739,
      "Serious,Critical": 1,
      "Tot Cases/1M pop": 341,
      "Deaths/1M pop": 0.8,
      "TotalTests": 68423,
      "Tests/1M pop": 29041,
      "WHO Region": "Africa"
    },
    {
      "Country/Region": "Bahamas",
      "Continent": "North America",
      "Population": 393616,
      "TotalCases": 761,
      "NewCases": "",
      "TotalDeaths": 14,
      "NewDeaths": "",
      "TotalRecovered": 91,
      "NewRecovered": "",
      "ActiveCases": 656,
      "Serious,Critical": 1,
      "Tot Cases/1M pop": 1933,
      "Deaths/1M pop": 36,
      "TotalTests": 4814,
      "Tests/1M pop": 12230,
      "WHO Region": "Americas"
    },
    {
      "Country/Region": "Vietnam",
      "Continent": "Asia",
      "Population": 97425470,
      "TotalCases": 747,
      "NewCases": "",
      "TotalDeaths": 10,
      "NewDeaths": "",
      "TotalRecovered": 392,
      "NewRecovered": "",
      "ActiveCases": 345,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 8,
      "Deaths/1M pop": 0.1,
      "TotalTests": 482456,
      "Tests/1M pop": 4952,
      "WHO Region": "WesternPacific"
    },
    {
      "Country/Region": "Lesotho",
      "Continent": "Africa",
      "Population": 2143943,
      "TotalCases": 742,
      "NewCases": "",
      "TotalDeaths": 23,
      "NewDeaths": "",
      "TotalRecovered": 175,
      "NewRecovered": "",
      "ActiveCases": 544,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 346,
      "Deaths/1M pop": 11,
      "TotalTests": 8771,
      "Tests/1M pop": 4091,
      "WHO Region": "Africa"
    },
    {
      "Country/Region": "Diamond Princess",
      "Continent": "",
      "Population": "",
      "TotalCases": 712,
      "NewCases": "",
      "TotalDeaths": 13,
      "NewDeaths": "",
      "TotalRecovered": 651,
      "NewRecovered": "",
      "ActiveCases": 48,
      "Serious,Critical": 4,
      "Tot Cases/1M pop": "",
      "Deaths/1M pop": "",
      "TotalTests": "",
      "Tests/1M pop": "",
      "WHO Region": ""
    },
    {
      "Country/Region": "San Marino",
      "Continent": "Europe",
      "Population": 33938,
      "TotalCases": 699,
      "NewCases": "",
      "TotalDeaths": 42,
      "NewDeaths": "",
      "TotalRecovered": 657,
      "NewRecovered": "",
      "ActiveCases": 0,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 20596,
      "Deaths/1M pop": 1238,
      "TotalTests": 6068,
      "Tests/1M pop": 178797,
      "WHO Region": "Europe"
    },
    {
      "Country/Region": "Réunion",
      "Continent": "Africa",
      "Population": 895952,
      "TotalCases": 671,
      "NewCases": "",
      "TotalDeaths": 5,
      "NewDeaths": "",
      "TotalRecovered": 592,
      "NewRecovered": "",
      "ActiveCases": 74,
      "Serious,Critical": 3,
      "Tot Cases/1M pop": 749,
      "Deaths/1M pop": 6,
      "TotalTests": 35419,
      "Tests/1M pop": 39532,
      "WHO Region": ""
    },
    {
      "Country/Region": "Channel Islands",
      "Continent": "Europe",
      "Population": 174022,
      "TotalCases": 597,
      "NewCases": "",
      "TotalDeaths": 47,
      "NewDeaths": "",
      "TotalRecovered": 533,
      "NewRecovered": "",
      "ActiveCases": 17,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 3431,
      "Deaths/1M pop": 270,
      "TotalTests": 30721,
      "Tests/1M pop": 176535,
      "WHO Region": ""
    },
    {
      "Country/Region": "Guyana",
      "Continent": "South America",
      "Population": 786936,
      "TotalCases": 538,
      "NewCases": "",
      "TotalDeaths": 22,
      "NewDeaths": "",
      "TotalRecovered": 189,
      "NewRecovered": "",
      "ActiveCases": 327,
      "Serious,Critical": 2,
      "Tot Cases/1M pop": 684,
      "Deaths/1M pop": 28,
      "TotalTests": 5165,
      "Tests/1M pop": 6563,
      "WHO Region": "Americas"
    },
    {
      "Country/Region": "Tanzania",
      "Continent": "Africa",
      "Population": 59886383,
      "TotalCases": 509,
      "NewCases": "",
      "TotalDeaths": 21,
      "NewDeaths": "",
      "TotalRecovered": 183,
      "NewRecovered": "",
      "ActiveCases": 305,
      "Serious,Critical": 7,
      "Tot Cases/1M pop": 8,
      "Deaths/1M pop": 0.4,
      "TotalTests": "",
      "Tests/1M pop": "",
      "WHO Region": "Africa"
    },
    {
      "Country/Region": "Taiwan",
      "Continent": "Asia",
      "Population": 23821199,
      "TotalCases": 477,
      "NewCases": "",
      "TotalDeaths": 7,
      "NewDeaths": "",
      "TotalRecovered": 443,
      "NewRecovered": "",
      "ActiveCases": 27,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 20,
      "Deaths/1M pop": 0.3,
      "TotalTests": 82737,
      "Tests/1M pop": 3473,
      "WHO Region": "WesternPacific"
    },
    {
      "Country/Region": "Comoros",
      "Continent": "Africa",
      "Population": 871326,
      "TotalCases": 396,
      "NewCases": "",
      "TotalDeaths": 7,
      "NewDeaths": "",
      "TotalRecovered": 340,
      "NewRecovered": "",
      "ActiveCases": 49,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 454,
      "Deaths/1M pop": 8,
      "TotalTests": "",
      "Tests/1M pop": "",
      "WHO Region": "Africa"
    },
    {
      "Country/Region": "Burundi",
      "Continent": "Africa",
      "Population": 11922216,
      "TotalCases": 395,
      "NewCases": "",
      "TotalDeaths": 1,
      "NewDeaths": "",
      "TotalRecovered": 304,
      "NewRecovered": "",
      "ActiveCases": 90,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 33,
      "Deaths/1M pop": 0.08,
      "TotalTests": 15614,
      "Tests/1M pop": 1310,
      "WHO Region": "Africa"
    },
    {
      "Country/Region": "Myanmar",
      "Continent": "Asia",
      "Population": 54446389,
      "TotalCases": 357,
      "NewCases": "",
      "TotalDeaths": 6,
      "NewDeaths": "",
      "TotalRecovered": 308,
      "NewRecovered": "",
      "ActiveCases": 43,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 7,
      "Deaths/1M pop": 0.1,
      "TotalTests": 122290,
      "Tests/1M pop": 2246,
      "WHO Region": "South-EastAsia"
    },
    {
      "Country/Region": "Mauritius",
      "Continent": "Africa",
      "Population": 1271985,
      "TotalCases": 344,
      "NewCases": "",
      "TotalDeaths": 10,
      "NewDeaths": "",
      "TotalRecovered": 334,
      "NewRecovered": "",
      "ActiveCases": 0,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 270,
      "Deaths/1M pop": 8,
      "TotalTests": 205285,
      "Tests/1M pop": 161389,
      "WHO Region": "Africa"
    },
    {
      "Country/Region": "Isle of Man",
      "Continent": "Europe",
      "Population": 85078,
      "TotalCases": 336,
      "NewCases": "",
      "TotalDeaths": 24,
      "NewDeaths": "",
      "TotalRecovered": 312,
      "NewRecovered": "",
      "ActiveCases": 0,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 3949,
      "Deaths/1M pop": 282,
      "TotalTests": 8627,
      "Tests/1M pop": 101401,
      "WHO Region": ""
    },
    {
      "Country/Region": "Mongolia",
      "Continent": "Asia",
      "Population": 3283344,
      "TotalCases": 293,
      "NewCases": "",
      "TotalDeaths": "",
      "NewDeaths": "",
      "TotalRecovered": 260,
      "NewRecovered": "",
      "ActiveCases": 33,
      "Serious,Critical": 1,
      "Tot Cases/1M pop": 89,
      "Deaths/1M pop": "",
      "TotalTests": 38334,
      "Tests/1M pop": 11675,
      "WHO Region": "WesternPacific"
    },
    {
      "Country/Region": "Eritrea",
      "Continent": "Africa",
      "Population": 3551175,
      "TotalCases": 282,
      "NewCases": "",
      "TotalDeaths": "",
      "NewDeaths": "",
      "TotalRecovered": 225,
      "NewRecovered": "",
      "ActiveCases": 57,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 79,
      "Deaths/1M pop": "",
      "TotalTests": "",
      "Tests/1M pop": "",
      "WHO Region": "Africa"
    },
    {
      "Country/Region": "Guadeloupe",
      "Continent": "North America",
      "Population": 400131,
      "TotalCases": 279,
      "NewCases": "",
      "TotalDeaths": 14,
      "NewDeaths": "",
      "TotalRecovered": 179,
      "NewRecovered": "",
      "ActiveCases": 86,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 697,
      "Deaths/1M pop": 35,
      "TotalTests": 18476,
      "Tests/1M pop": 46175,
      "WHO Region": ""
    },
    {
      "Country/Region": "Martinique",
      "Continent": "North America",
      "Population": 375235,
      "TotalCases": 276,
      "NewCases": "",
      "TotalDeaths": 15,
      "NewDeaths": "",
      "TotalRecovered": 98,
      "NewRecovered": "",
      "ActiveCases": 163,
      "Serious,Critical": 1,
      "Tot Cases/1M pop": 736,
      "Deaths/1M pop": 40,
      "TotalTests": 12227,
      "Tests/1M pop": 32585,
      "WHO Region": ""
    },
    {
      "Country/Region": "Faeroe Islands",
      "Continent": "Europe",
      "Population": 48882,
      "TotalCases": 266,
      "NewCases": "",
      "TotalDeaths": "",
      "NewDeaths": "",
      "TotalRecovered": 192,
      "NewRecovered": "",
      "ActiveCases": 74,
      "Serious,Critical": 1,
      "Tot Cases/1M pop": 5442,
      "Deaths/1M pop": "",
      "TotalTests": 43045,
      "Tests/1M pop": 880590,
      "WHO Region": ""
    },
    {
      "Country/Region": "Aruba",
      "Continent": "North America",
      "Population": 106812,
      "TotalCases": 263,
      "NewCases": "",
      "TotalDeaths": 3,
      "NewDeaths": "",
      "TotalRecovered": 114,
      "NewRecovered": "",
      "ActiveCases": 146,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 2462,
      "Deaths/1M pop": 28,
      "TotalTests": 14047,
      "Tests/1M pop": 131511,
      "WHO Region": ""
    },
    {
      "Country/Region": "Cambodia",
      "Continent": "Asia",
      "Population": 16741375,
      "TotalCases": 243,
      "NewCases": "",
      "TotalDeaths": "",
      "NewDeaths": "",
      "TotalRecovered": 210,
      "NewRecovered": "",
      "ActiveCases": 33,
      "Serious,Critical": 1,
      "Tot Cases/1M pop": 15,
      "Deaths/1M pop": "",
      "TotalTests": 67807,
      "Tests/1M pop": 4050,
      "WHO Region": "WesternPacific"
    },
    {
      "Country/Region": "Trinidad and Tobago",
      "Continent": "North America",
      "Population": 1399950,
      "TotalCases": 210,
      "NewCases": "",
      "TotalDeaths": 8,
      "NewDeaths": "",
      "TotalRecovered": 135,
      "NewRecovered": "",
      "ActiveCases": 67,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 150,
      "Deaths/1M pop": 6,
      "TotalTests": 9559,
      "Tests/1M pop": 6828,
      "WHO Region": "Americas"
    },
    {
      "Country/Region": "Cayman Islands",
      "Continent": "North America",
      "Population": 65798,
      "TotalCases": 203,
      "NewCases": "",
      "TotalDeaths": 1,
      "NewDeaths": "",
      "TotalRecovered": 202,
      "NewRecovered": "",
      "ActiveCases": 0,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 3085,
      "Deaths/1M pop": 15,
      "TotalTests": 31108,
      "Tests/1M pop": 472780,
      "WHO Region": ""
    },
    {
      "Country/Region": "Gibraltar",
      "Continent": "Europe",
      "Population": 33690,
      "TotalCases": 190,
      "NewCases": "",
      "TotalDeaths": "",
      "NewDeaths": "",
      "TotalRecovered": 184,
      "NewRecovered": "",
      "ActiveCases": 6,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 5640,
      "Deaths/1M pop": "",
      "TotalTests": 23063,
      "Tests/1M pop": 684565,
      "WHO Region": ""
    },
    {
      "Country/Region": "Papua New Guinea",
      "Continent": "Australia/Oceania",
      "Population": 8963009,
      "TotalCases": 163,
      "NewCases": "",
      "TotalDeaths": 3,
      "NewDeaths": "",
      "TotalRecovered": 53,
      "NewRecovered": "",
      "ActiveCases": 107,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 18,
      "Deaths/1M pop": 0.3,
      "TotalTests": 10808,
      "Tests/1M pop": 1206,
      "WHO Region": "WesternPacific"
    },
    {
      "Country/Region": "Sint Maarten",
      "Continent": "North America",
      "Population": 42924,
      "TotalCases": 160,
      "NewCases": "",
      "TotalDeaths": 16,
      "NewDeaths": "",
      "TotalRecovered": 64,
      "NewRecovered": "",
      "ActiveCases": 80,
      "Serious,Critical": 3,
      "Tot Cases/1M pop": 3728,
      "Deaths/1M pop": 373,
      "TotalTests": 1115,
      "Tests/1M pop": 25976,
      "WHO Region": ""
    },
    {
      "Country/Region": "Bermuda",
      "Continent": "North America",
      "Population": 62254,
      "TotalCases": 157,
      "NewCases": "",
      "TotalDeaths": 9,
      "NewDeaths": "",
      "TotalRecovered": 144,
      "NewRecovered": "",
      "ActiveCases": 4,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 2522,
      "Deaths/1M pop": 145,
      "TotalTests": 26352,
      "Tests/1M pop": 423298,
      "WHO Region": "Americas"
    },
    {
      "Country/Region": "Brunei",
      "Continent": "Asia",
      "Population": 437893,
      "TotalCases": 141,
      "NewCases": "",
      "TotalDeaths": 3,
      "NewDeaths": "",
      "TotalRecovered": 138,
      "NewRecovered": "",
      "ActiveCases": 0,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 322,
      "Deaths/1M pop": 7,
      "TotalTests": 41148,
      "Tests/1M pop": 93968,
      "WHO Region": ""
    },
    {
      "Country/Region": "Barbados",
      "Continent": "North America",
      "Population": 287411,
      "TotalCases": 133,
      "NewCases": "",
      "TotalDeaths": 7,
      "NewDeaths": "",
      "TotalRecovered": 100,
      "NewRecovered": "",
      "ActiveCases": 26,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 463,
      "Deaths/1M pop": 24,
      "TotalTests": 12233,
      "Tests/1M pop": 42563,
      "WHO Region": "Americas"
    },
    {
      "Country/Region": "Turks and Caicos",
      "Continent": "North America",
      "Population": 38768,
      "TotalCases": 129,
      "NewCases": "",
      "TotalDeaths": 2,
      "NewDeaths": "",
      "TotalRecovered": 39,
      "NewRecovered": "",
      "ActiveCases": 88,
      "Serious,Critical": 3,
      "Tot Cases/1M pop": 3327,
      "Deaths/1M pop": 52,
      "TotalTests": 1252,
      "Tests/1M pop": 32295,
      "WHO Region": ""
    },
    {
      "Country/Region": "Seychelles",
      "Continent": "Africa",
      "Population": 98408,
      "TotalCases": 126,
      "NewCases": "",
      "TotalDeaths": "",
      "NewDeaths": "",
      "TotalRecovered": 124,
      "NewRecovered": "",
      "ActiveCases": 2,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 1280,
      "Deaths/1M pop": "",
      "TotalTests": "",
      "Tests/1M pop": "",
      "WHO Region": "Africa"
    },
    {
      "Country/Region": "Monaco",
      "Continent": "Europe",
      "Population": 39270,
      "TotalCases": 125,
      "NewCases": "",
      "TotalDeaths": 4,
      "NewDeaths": "",
      "TotalRecovered": 105,
      "NewRecovered": "",
      "ActiveCases": 16,
      "Serious,Critical": 2,
      "Tot Cases/1M pop": 3183,
      "Deaths/1M pop": 102,
      "TotalTests": 38209,
      "Tests/1M pop": 972982,
      "WHO Region": "Europe"
    },
    {
      "Country/Region": "Bhutan",
      "Continent": "Asia",
      "Population": 772443,
      "TotalCases": 105,
      "NewCases": "",
      "TotalDeaths": "",
      "NewDeaths": "",
      "TotalRecovered": 93,
      "NewRecovered": "",
      "ActiveCases": 12,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 136,
      "Deaths/1M pop": "",
      "TotalTests": 54589,
      "Tests/1M pop": 70671,
      "WHO Region": "South-EastAsia"
    },
    {
      "Country/Region": "Antigua and Barbuda",
      "Continent": "North America",
      "Population": 98010,
      "TotalCases": 92,
      "NewCases": "",
      "TotalDeaths": 3,
      "NewDeaths": "",
      "TotalRecovered": 76,
      "NewRecovered": "",
      "ActiveCases": 13,
      "Serious,Critical": 1,
      "Tot Cases/1M pop": 939,
      "Deaths/1M pop": 31,
      "TotalTests": 1500,
      "Tests/1M pop": 15305,
      "WHO Region": "Americas"
    },
    {
      "Country/Region": "Liechtenstein",
      "Continent": "Europe",
      "Population": 38139,
      "TotalCases": 89,
      "NewCases": "",
      "TotalDeaths": 1,
      "NewDeaths": "",
      "TotalRecovered": 85,
      "NewRecovered": "",
      "ActiveCases": 3,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 2334,
      "Deaths/1M pop": 26,
      "TotalTests": 900,
      "Tests/1M pop": 23598,
      "WHO Region": "Europe"
    },
    {
      "Country/Region": "Belize",
      "Continent": "North America",
      "Population": 398312,
      "TotalCases": 86,
      "NewCases": "",
      "TotalDeaths": 2,
      "NewDeaths": "",
      "TotalRecovered": 31,
      "NewRecovered": "",
      "ActiveCases": 53,
      "Serious,Critical": 2,
      "Tot Cases/1M pop": 216,
      "Deaths/1M pop": 5,
      "TotalTests": 3679,
      "Tests/1M pop": 9236,
      "WHO Region": "Americas"
    },
    {
      "Country/Region": "French Polynesia",
      "Continent": "Australia/Oceania",
      "Population": 281072,
      "TotalCases": 64,
      "NewCases": "",
      "TotalDeaths": "",
      "NewDeaths": "",
      "TotalRecovered": 62,
      "NewRecovered": "",
      "ActiveCases": 2,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 228,
      "Deaths/1M pop": "",
      "TotalTests": 5849,
      "Tests/1M pop": 20810,
      "WHO Region": ""
    },
    {
      "Country/Region": "St. Vincent Grenadines",
      "Continent": "North America",
      "Population": 110976,
      "TotalCases": 56,
      "NewCases": "",
      "TotalDeaths": "",
      "NewDeaths": "",
      "TotalRecovered": 46,
      "NewRecovered": "",
      "ActiveCases": 10,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 505,
      "Deaths/1M pop": "",
      "TotalTests": 2447,
      "Tests/1M pop": 22050,
      "WHO Region": ""
    },
    {
      "Country/Region": "Saint Martin",
      "Continent": "North America",
      "Population": 38729,
      "TotalCases": 53,
      "NewCases": "",
      "TotalDeaths": 3,
      "NewDeaths": "",
      "TotalRecovered": 41,
      "NewRecovered": "",
      "ActiveCases": 9,
      "Serious,Critical": 1,
      "Tot Cases/1M pop": 1368,
      "Deaths/1M pop": 77,
      "TotalTests": 1183,
      "Tests/1M pop": 30546,
      "WHO Region": ""
    },
    {
      "Country/Region": "Macao",
      "Continent": "Asia",
      "Population": 650193,
      "TotalCases": 46,
      "NewCases": "",
      "TotalDeaths": "",
      "NewDeaths": "",
      "TotalRecovered": 46,
      "NewRecovered": "",
      "ActiveCases": 0,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 71,
      "Deaths/1M pop": "",
      "TotalTests": 4071,
      "Tests/1M pop": 6261,
      "WHO Region": ""
    },
    {
      "Country/Region": "Curaçao",
      "Continent": "North America",
      "Population": 164161,
      "TotalCases": 31,
      "NewCases": "",
      "TotalDeaths": 1,
      "NewDeaths": "",
      "TotalRecovered": 28,
      "NewRecovered": "",
      "ActiveCases": 2,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 189,
      "Deaths/1M pop": 6,
      "TotalTests": 1080,
      "Tests/1M pop": 6579,
      "WHO Region": ""
    },
    {
      "Country/Region": "Fiji",
      "Continent": "Australia/Oceania",
      "Population": 897095,
      "TotalCases": 27,
      "NewCases": "",
      "TotalDeaths": 1,
      "NewDeaths": "",
      "TotalRecovered": 18,
      "NewRecovered": "",
      "ActiveCases": 8,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 30,
      "Deaths/1M pop": 1,
      "TotalTests": 6693,
      "Tests/1M pop": 7461,
      "WHO Region": "WesternPacific"
    },
    {
      "Country/Region": "Saint Lucia",
      "Continent": "North America",
      "Population": 183712,
      "TotalCases": 25,
      "NewCases": "",
      "TotalDeaths": "",
      "NewDeaths": "",
      "TotalRecovered": 24,
      "NewRecovered": "",
      "ActiveCases": 1,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 136,
      "Deaths/1M pop": "",
      "TotalTests": 3895,
      "Tests/1M pop": 21202,
      "WHO Region": "Americas"
    },
    {
      "Country/Region": "Timor-Leste",
      "Continent": "Asia",
      "Population": 1320812,
      "TotalCases": 25,
      "NewCases": "",
      "TotalDeaths": "",
      "NewDeaths": "",
      "TotalRecovered": 24,
      "NewRecovered": "",
      "ActiveCases": 1,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 19,
      "Deaths/1M pop": "",
      "TotalTests": 4238,
      "Tests/1M pop": 3209,
      "WHO Region": "South-EastAsia"
    },
    {
      "Country/Region": "Grenada",
      "Continent": "North America",
      "Population": 112576,
      "TotalCases": 24,
      "NewCases": "",
      "TotalDeaths": "",
      "NewDeaths": "",
      "TotalRecovered": 23,
      "NewRecovered": "",
      "ActiveCases": 1,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 213,
      "Deaths/1M pop": "",
      "TotalTests": 6252,
      "Tests/1M pop": 55536,
      "WHO Region": "Americas"
    },
    {
      "Country/Region": "New Caledonia",
      "Continent": "Australia/Oceania",
      "Population": 285769,
      "TotalCases": 22,
      "NewCases": "",
      "TotalDeaths": "",
      "NewDeaths": "",
      "TotalRecovered": 22,
      "NewRecovered": "",
      "ActiveCases": 0,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 77,
      "Deaths/1M pop": "",
      "TotalTests": 11099,
      "Tests/1M pop": 38839,
      "WHO Region": ""
    },
    {
      "Country/Region": "Laos",
      "Continent": "Asia",
      "Population": 7285750,
      "TotalCases": 20,
      "NewCases": "",
      "TotalDeaths": "",
      "NewDeaths": "",
      "TotalRecovered": 19,
      "NewRecovered": "",
      "ActiveCases": 1,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 3,
      "Deaths/1M pop": "",
      "TotalTests": 29374,
      "Tests/1M pop": 4032,
      "WHO Region": "WesternPacific"
    },
    {
      "Country/Region": "Dominica",
      "Continent": "North America",
      "Population": 72004,
      "TotalCases": 18,
      "NewCases": "",
      "TotalDeaths": "",
      "NewDeaths": "",
      "TotalRecovered": 18,
      "NewRecovered": "",
      "ActiveCases": 0,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 250,
      "Deaths/1M pop": "",
      "TotalTests": 1005,
      "Tests/1M pop": 13958,
      "WHO Region": "Americas"
    },
    {
      "Country/Region": "Saint Kitts and Nevis",
      "Continent": "North America",
      "Population": 53237,
      "TotalCases": 17,
      "NewCases": "",
      "TotalDeaths": "",
      "NewDeaths": "",
      "TotalRecovered": 16,
      "NewRecovered": "",
      "ActiveCases": 1,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 319,
      "Deaths/1M pop": "",
      "TotalTests": 1146,
      "Tests/1M pop": 21526,
      "WHO Region": "Americas"
    },
    {
      "Country/Region": "Greenland",
      "Continent": "North America",
      "Population": 56780,
      "TotalCases": 14,
      "NewCases": "",
      "TotalDeaths": "",
      "NewDeaths": "",
      "TotalRecovered": 14,
      "NewRecovered": "",
      "ActiveCases": 0,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 247,
      "Deaths/1M pop": "",
      "TotalTests": 5977,
      "Tests/1M pop": 105266,
      "WHO Region": "Europe"
    },
    {
      "Country/Region": "Montserrat",
      "Continent": "North America",
      "Population": 4992,
      "TotalCases": 13,
      "NewCases": "",
      "TotalDeaths": 1,
      "NewDeaths": "",
      "TotalRecovered": 10,
      "NewRecovered": "",
      "ActiveCases": 2,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 2604,
      "Deaths/1M pop": 200,
      "TotalTests": 61,
      "Tests/1M pop": 12220,
      "WHO Region": ""
    },
    {
      "Country/Region": "Caribbean Netherlands",
      "Continent": "North America",
      "Population": 26247,
      "TotalCases": 13,
      "NewCases": "",
      "TotalDeaths": "",
      "NewDeaths": "",
      "TotalRecovered": 7,
      "NewRecovered": "",
      "ActiveCases": 6,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 495,
      "Deaths/1M pop": "",
      "TotalTests": 424,
      "Tests/1M pop": 16154,
      "WHO Region": ""
    },
    {
      "Country/Region": "Falkland Islands",
      "Continent": "South America",
      "Population": 3489,
      "TotalCases": 13,
      "NewCases": "",
      "TotalDeaths": "",
      "NewDeaths": "",
      "TotalRecovered": 13,
      "NewRecovered": "",
      "ActiveCases": 0,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 3726,
      "Deaths/1M pop": "",
      "TotalTests": 1816,
      "Tests/1M pop": 520493,
      "WHO Region": ""
    },
    {
      "Country/Region": "Vatican City",
      "Continent": "Europe",
      "Population": 801,
      "TotalCases": 12,
      "NewCases": "",
      "TotalDeaths": "",
      "NewDeaths": "",
      "TotalRecovered": 12,
      "NewRecovered": "",
      "ActiveCases": 0,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 14981,
      "Deaths/1M pop": "",
      "TotalTests": "",
      "Tests/1M pop": "",
      "WHO Region": "Europe"
    },
    {
      "Country/Region": "Western Sahara",
      "Continent": "Africa",
      "Population": 598682,
      "TotalCases": 10,
      "NewCases": "",
      "TotalDeaths": 1,
      "NewDeaths": "",
      "TotalRecovered": 8,
      "NewRecovered": "",
      "ActiveCases": 1,
      "Serious,Critical": "",
      "Tot Cases/1M pop": 17,
      "Deaths/1M pop": 2,
      "TotalTests": "",
      "Tests/1M pop": "",
      "WHO Region": "Africa"
    }
  ]
  return (
    <Main data={data}/>
  );
}

export default App;
